### ISSUE TITLE
Failed Import

### ISSUE THREAD

**Issue by mlaforge64** [rmcrackan/Libation#715] opened 2023-08-17 11:57 UTC
[Log202308.zip](https://github.com/rmcrackan/Libation/files/12369035/Log202308.zip)
Following the instructions after a failed library import.
I tried several times on two computers and receive the same error

**Comment by Mbucari** [comment] 2023-08-17 18:03
@mlaforge64 Thanks for the report. This will be fixed shortly.

Out of curiosity, are you subscribe to [the THE JORDAN
HARBINGER SHOW](https://www.audible.com/pd/The-Jordan-Harbinger-Show-Podcast/B08K57HXZS)? I ask because I got the same error today and it was caused by the most recent episode of that podcast.

**Comment by rmcrackan** [comment] 2023-08-17 18:17
Oh god don't tell me about podcast like this one. In my transition from podcast addict to audiobook addict I tried to keep up with several very good long form interview podcasts and also have time for audiobooks. It was ugly.

**Comment by Mbucari** [comment] 2023-08-17 18:20
The secret is to live very far away from your office and have an atrocious commute.

**Comment by rmcrackan** [comment] 2023-08-17 18:32
[Fixed in version 11.0.1](https://github.com/rmcrackan/Libation/releases/latest)

**Comment by mlaforge64** [comment] 2023-08-17 18:33
I don't subscribe to that one, But I agree with you about the commute. I live an hour and an half away from my shop and can't imagine life without audiobooks and Podcasts

**Closed by rmcrackan** 2023-08-17 18:32 UTC

**Comment by mlaforge64** [comment] 2023-08-17 18:36
Outstanding! Thank you for your quick response and repair!
