### ISSUE TITLE
Decrypt to Author folders

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#95] opened 2021-08-29 19:22 UTC
Enhancement request. I've got a LOT of books across multiple accounts. It would be highly useful to have the ability to have the decrypted files stored in the location: < base >\\< authorname >\\< booktitle >   instead of the current: < base >\\<booktitle>

Thanks!

**Comment by wtanksleyjr** [comment] 2021-08-30 00:07
Not a bad idea, but I'd say this is more of an opportunity for an automatic renamer. (My accounts have 1900+ titles.) There's a nice opportunity, especially since Libation downloads and can export all of the book's data; I use that myself to place the books into a unified location (although my system is Unix-specific, it uses hardlinks).

**Comment by rmcrackan** [comment] 2021-08-30 01:25
This is a duplicate of #50 so I'm going to close this one.

I love the idea behind customizable output paths and I've sketched out initial concepts. If I get the time I'll definitely work through my work queue and get to this eventually.

I have so many great ideas to help out the users and so little time. Not to mention family and a paying job. If someone could please get Bezos to fund me instead of eventually sending me an inevitable cease and desist, that'd be fantastic.

**Closed by rmcrackan** 2021-08-30 01:25 UTC
