### ISSUE TITLE
LibationCli crashes if Settings.json is readonly

### ISSUE THREAD

**Issue by pixil98** [rmcrackan/Libation#354] opened 2022-08-12 05:16 UTC
**Describe the bug**
LibationCli crashes with the following error if Settings.json is on a read only filesystem.

```
Unhandled exception. System.IO.IOException: Read-only file system : '/root/Libation/Settings.json'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at FileManager.PersistentDictionary.writeFile(String propertyName, JToken newValue) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\FileManager\PersistentDictionary.cs:line 131
   at FileManager.PersistentDictionary.SetNonString(String propertyName, Object newValue) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\FileManager\PersistentDictionary.cs:line 114
   at LibationFileManager.Configuration.set_BetaOptIn(Boolean value) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\LibationFileManager\Configuration.cs:line 81
   at AppScaffolding.LibationScaffolding.PopulateMissingConfigValues(Configuration config) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\AppScaffolding\LibationScaffolding.cs:line 96
   at AppScaffolding.LibationScaffolding.RunPostConfigMigrations(Configuration config) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\AppScaffolding\LibationScaffolding.cs:line 81
   at LibationCli.Setup.Initialize() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\LibationCli\Setup.cs:line 24
   at LibationCli.Program.Main(String[] args) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\LibationCli\Program.cs:line 29
   at LibationCli.Program.<Main>(String[] args)
```

I haven't gotten far enough to check if this problem will occur with AccountSettings.json as well, but I suspect it will.

**To Reproduce**
I caused this by creating a docker container, running it in kubernetes, and mounting the Settings.json in via configmap. I imagine it could also be reproduced by putting your Libation config folder on a usb drive and mounting that drive read only. 

**Expected behavior**
I expect it to be happy using a read only file that it isn't going to modify.

**Platform**
Linux

**Log Files**
As far as I can tell it didn't log anything.

**Comment by rmcrackan** [comment] 2022-08-12 11:33
Sorry, Libation needs write access to that folder. That's also where the search engine and logs are created. To use a different director for this, go to the folder Libation lives in and open appsettings.json. The path this points to that dir with Setings, log files, search engine, etc. Modify the path in appsettings.json to use a folder with write permissions.

I'm closing this ticket because it's a necessary part of the system; not a bug. However if you reply here I'll still see it. Is there anything we can do to facilitate configuring Libation for your case?

**Closed by rmcrackan** 2022-08-12 11:33 UTC
Labels: bug

**Comment by rmcrackan** [comment] 2022-08-12 11:44
> However if you reply here I'll still see it. Is there anything we can do to facilitate configuring Libation for your case?

Ah, you can ignore my last bit since your feature request appears to be exactly this 😄

**Comment by pixil98** [comment] 2022-08-12 14:57
I do think this is still a bug. In my case it does actually have write access to the folder, just not Settings.json or AccountSettings.json which have been volume mounted in a read only. You could more accurately replicate my setup by placing the two json files on a usb drive that is mounted read only and then creating a symlink to them from /home/<user>/Libation. That way the Libation folder is still writable but the json files themselves are not.

**Comment by rmcrackan** [comment] 2022-08-12 15:19
Part of the startup is ensuring a valid Settings.json file for the current version. If it's up to date, then it will not be written to. In the case above, it was missing one of the newer config settings. Libation attempted to add that setting (BetaOptIn) and its default value (false) to your Settings file.

If you run Libation as non-readonly then you'll get a newly updated settings file which will work in your read-only environment.

**Comment by pixil98** [comment] 2022-08-12 19:36
Fair enough, that's a pretty reasonable reason to write to it.
