### ISSUE TITLE
Crash when attempting to download.

### ISSUE THREAD

**Issue by fantoams18** [rmcrackan/Libation#292] opened 2022-06-22 21:55 UTC
[Log202206_001.log](https://github.com/rmcrackan/Libation/files/8961605/Log202206_001.log)

Scans fine. Sees new titles. Click to download and it appears on the right. Calculates time. Crashes out.

Tried removing and re-adding account info.

**Comment by rmcrackan** [comment] 2022-06-23 17:04
So sorry about the crashing. Thanks for the log. Please delete the files in `C:\Users\Phils\Documents\Libation\DownloadsInProgress` and try again. If you're still crashing, please attach the new log file.

**Comment by rmcrackan** [comment] 2022-06-24 01:08
Thank you for your patience. See if [version 8.1.2](https://github.com/rmcrackan/Libation/releases/latest) solves your issue. If it doesn't, it should at least give us much better logs to figure this out.

**Comment by rmcrackan** [comment] 2022-06-24 01:58
Duplicate of #294

**Closed by rmcrackan** 2022-06-24 01:58 UTC
Labels: bug

**Comment by rmcrackan** [comment] 2022-06-24 01:59
Since this issue #294 are the same bug, I'm going to consolidate these so I only have to track them in one place. If you reply in either place though, I'll see you. Sorry for this bug. I'm not sure what I did wrong but we're on the case until this is resolved.
