### ISSUE TITLE
MP3 Decode Cuts Audiobook Duration To Around 4 Hours

### ISSUE THREAD

**Issue by sgmax** [rmcrackan/Libation#104] opened 2021-09-07 18:15 UTC
Using the MP3 encoding option cuts off the audiobook at around 4 hours (ish). I attach the log for my books - I noticed this yesterday when I tried to decode eight books to mp3 and ended up with durations around the 4 hour mark for all eight., 
I re-ran the downloads/decrypts in .M4B and the audiobook duration was set correctly (between 7 to 9+ hrs duration).
I also tried the download decode with and without the "Fix up metadata" option checked - the .M4B option works in both modes.
So it is definitely the MP3 decode that is stopping around halfway through. As the lengths are all in the ballpark of 4 hrs (plus or minus), I'm guessing a temporary counter/timer variable is to blame.
My default MP3 decoder is Lame_v3.100 (although it looks as if you use your own decoder, so this may be extraneous info).
I attach a verbose log for the MP3 decode (which I ran for just 2 of the decodes as an FYI).
I repeated these two decodes for an MP4 decode with the "Fix up metadata" option checked. 
Let me know if you need additional information.
Just wanted to say that I LOVE the software app - this is really helpful - many thanks!
[Log202109.log](https://github.com/rmcrackan/Libation/files/7123498/Log202109.log)
![Libation-Settings  MP3](https://user-images.githubusercontent.com/28791733/132390888-a24733b1-0cc9-4248-9f10-3771a528211c.jpg)
![Library Extract  showing lengths of books](https://user-images.githubusercontent.com/28791733/132390898-ea15fcd3-6da5-462f-9443-fe32ac48c8dd.JPG)
![Metadata-B002V8KQU8-mp3](https://user-images.githubusercontent.com/28791733/132390922-31eb2d8f-607a-448a-a421-734f16b81f38.JPG)
![Metadata-B002V8KQU8-m4b](https://user-images.githubusercontent.com/28791733/132390924-e316fc6d-7d04-4c06-befd-e869791ffe22.JPG)
![Metadata-B005KBQUKS-mp3](https://user-images.githubusercontent.com/28791733/132390925-ba6b5640-8e41-48a1-84ad-c1a7fa04ac90.JPG)
![Metadata-B005KBQUKS-m4b](https://user-images.githubusercontent.com/28791733/132390928-947716d4-809b-4c8e-b64d-156458bda061.JPG)

**Comment by Mbucari** [comment] 2021-09-08 03:34
Strange. I tested that title and it decrypted directly to mp3 without error. Mind uploading your logs?

**Comment by Mbucari** [comment] 2021-09-08 16:00
@sgmax I'm the maintainer of the decryptor/encoder module.  Like I said, I'm not able to reproduce your error. The final mp3 file size is 134 MB.  I play it in PotPlayer and Groove Music, and Windows Media Player, and all of them detect and can play the full 9:32.

Can you please link to the decoder software you're using?

**Comment by sgmax** [comment] 2021-09-08 18:57
Hiya -
      Thanks for getting back to me. I thought I did upload the Libation
Log file to github. Can you let me know which additional file to upload?

I am using Foobar 2000 to play back audio files (updated last week to
v1.6.7). This is the standard installation (no customized codecs
installed).The length reported by Foobar is 4 hrs 54s - it does stop
playing the book at the 4:54 mark in the story, so this is not just a
display problem - Foobar thinks it is only 4:54 long (as with all the other
files I encoded as mp3, which were all reported as around 4+ hours long).

After you mentioned that you could not reproduce this issue, I tried
playing the file in VLC and it displayed the whole file length.
The duration displayed in VLC  vacillated between 9 hrs 30 mins and 10 hrs
5 mins in VLC (is this a VBR file?), so I also tried playing the file in
Windows Media Player (😈). That displayed a length of 9:34:38.
Interestingly, Foobar reports the file as 64kbs CBR, but Windows 10 file
properties report it as 32 kbs. Another (sound recorder) player reports it
as 22 kbs. So there is something strange going on with the file properties
in some decoders.

So it does look as if the problem lies in the mp3 decoder. As Foobar 2000
is a pretty common music player, I'm surprised I am the first person to
fall over this.
I'm not sure which is the salient codec (possibly FFmeg Decoders?) so here
is the complete list from my install of Foobar 2000:
Core (2021-08-09 13:53:58 UTC) - foobar2000 core 1.6.7
foo_albumlist.dll (2021-08-09 13:53:28 UTC) - Album List 1.6.7
foo_cdda.dll (2021-08-09 13:53:28 UTC) - CD Audio Decoder 1.6.7
foo_converter.dll (2021-08-09 13:53:30 UTC) - Converter 1.6.7
foo_dsp_eq.dll (2021-08-09 13:53:22 UTC) - Equalizer 1.2.2
foo_dsp_std.dll (2021-08-09 13:53:28 UTC) - Standard DSP Array 1.6.7
foo_fileops.dll (2021-08-09 13:53:30 UTC) - File Operations 1.6.7
foo_freedb2.dll (2021-08-09 13:53:30 UTC) - Online Tagger 0.8
foo_input_std.dll (2021-08-09 13:53:40 UTC) - FFmpeg Decoders 4.3.1;
Standard Input Array 1.6.7
foo_rgscan.dll (2021-08-09 13:53:32 UTC) - ReplayGain Scanner 1.6.7
foo_ui_std.dll (2021-08-09 13:53:42 UTC) - Default User Interface 1.6.7
foo_unpack.dll (2021-08-09 13:53:46 UTC) - ZIP/GZIP/RAR/7-Zip Reader 1.6.7

Do you want to take this up with the Foobar guys, or should I?
Have fun!

Cheers,
           Susan

**Comment by Mbucari** [comment] 2021-09-10 16:10
Sorry it's taking so long to get around to this. I've been occupied with other things.

It might be a good idea to open a ticket with foobar.  Here's some info on the re-encoding implementation to pass along to the foobar people:

Decode aac to 16-bit PCM using FDK-AAC v2.0.2. Encode to mp3 using NAudio.Lame. LameConfig options: Mode = Mono, VBR = ABR, ABRRateKbps  = 1/2 source bitrate (source is stereo, so downsampling to mono needs only half the bitrate)

**Comment by rmcrackan** [comment] 2021-09-10 21:44
Reopened. See #110 for more info

**Comment by Mbucari** [comment] 2021-09-11 04:45
Thanks for the info. I'll look into it this weekend. If it's just an optional header that might be easy enough to tack on to the end of re-encoding task.

**Comment by rmcrackan** [comment] 2021-09-16 11:59
Fixed in [v5.7.5](https://github.com/rmcrackan/Libation/releases/latest)

**Closed by rmcrackan** 2021-09-16 11:59 UTC
