### ISSUE TITLE
Not all PDFs are actually downloaded

### ISSUE THREAD

**Issue by wrampy** [rmcrackan/Libation#430] opened 2022-12-28 21:32 UTC
**Describe the bug**
10 books in my library have accompanying PDFs. But when I search the Libation library folder there are only 2 PDFs.
Libation shows the PDF icon for all 10 audiobooks. The Liberate menu shows "All PDFs have been downloaded".
Clicking the PDF icon opens the proper directory in Nautilus, but these contain only CUE, JPG and M4B files, no PDF (except for the above mentioned 2 audiobooks).

**To Reproduce**
Opened Libation. Clicked the Liberate - "All PDFs have been downloaded" menu item. Nothing happened. Logs still show all 10 PDFs are downloaded.
I removed one of the audiobooks from Libation library. I also deleted the files. Rescanned my Audible library, which detected the now missing audiobook which the application successfully liberated, but there is still no PDF next to it. I do not see in the logs any attempt for downloading the PDF.
I can download the PDF from audible.com with a browser.

**Expected behavior**
All the accompanying PDFs properly downloaded.
A button or menu item to enforce PDF re-download.
Logs to show the path of the PDF where it was saved.

**Platform**
Linux (Ubuntu 22.04)
Version 8.5.1.1

**Log Files**
[Log202212.log](https://github.com/rmcrackan/Libation/files/10316562/Log202212.log)

**Comment by rmcrackan** [comment] 2022-12-28 22:25
Sorry about this. Do you still have the older log from when the pdfs were downloaded? If so, can you also attach them to this bug? I'm curious to know if they could shed some light.

**Comment by wrampy** [comment] 2022-12-29 07:33
No, I don't have the old logs, but I can reproduce the behavior.

When I first downloaded the whole library I run into issues due to filenames being too long. Therefore I changed the filename pattern in the settings and re-downloaded/liberated all the audiobooks. And it looks like the PDFs were not downloaded after the first time. The two audiobooks that have the PDFs were added later, so there was no re-downloading.

Steps to reproduce:
1. search for the book
2. click the "Set the Downloaded status manually..." menu item under "Visible books"
3. change it to "Not Downloaded" and save it
4. the semaphore lights next to the book will change to red
5. the menu items under "Liberate" show that 1 audiobook needs liberation, but all PDFs were downloaded ![libation](https://user-images.githubusercontent.com/71339764/209918274-939239f7-6b57-4114-83ee-414914bc3fed.png)

You can see this behavior in the logs I already attached.

It looks like only the "Not Downloaded" status applies only to the audio file, not to the PDF, so the application won't try to download the PDF ever again.

**Comment by Mbucari** [comment] 2022-12-29 07:52
@wrampy What's the filesystem of the disk where you're saving your books?

**Comment by wrampy** [comment] 2022-12-29 08:20
@Mbucari ext4

**Comment by Mbucari** [comment] 2022-12-29 09:12
@wrampy Regarding PDF download status, there is no way to batch change PDF download statuses. However, you may change each book's PDF status manually by clicking on the book tags button in the main grid like so:


![VirtualBox_Ubuntu 22_29_12_2022_02_02_10](https://user-images.githubusercontent.com/37587114/209929413-fb198138-18d6-437c-a857-bff6d2214450.png)

As for the log files, would you please reproduce the error on your machine and attach a log file containing a failed PDF download attempt?

**Comment by wrampy** [comment] 2022-12-29 09:32
Great, now it works. This is more of a UI/UX issue, as a user who opens this application 1-2x a month I don't know about all these hidden features. So far I did everything from the main menu and never opened this dialog of an individual book. I would recommend to extend the batch download status change functionality for PDFs (or at least put a hint there that those changes won't apply to PDFs).

![libation2](https://user-images.githubusercontent.com/71339764/209931475-0513901b-88a3-4616-a3b8-ec2a858ed96c.png)

And the logs [Log202212.log](https://github.com/rmcrackan/Libation/files/10318634/Log202212.log)

**Comment by Mbucari** [comment] 2022-12-29 09:37
I think at one point libation did have an option to set PDF statuses on all visible books, and I'm not sure what happened to it.

File names longer than Max path should be truncated, so books failing to download because of file name length is a Libation bug. I'll look into it more tomorrow.

**Comment by wrampy** [comment] 2022-12-29 10:21
This was one of the books that had issues because of the long filenames:
Author: "Dr. Aziz Gazipura PsyD"
Title: "Not Nice"
Subtitle: "Stop People Pleasing, Staying Silent, & Feeling Guilty... And Start Speaking up, Saying No, Asking Boldly, and Unapologetically Being Yourself"

It has a ridiculously long subtitle. Totally 23 + 8 + 143 = 174 characters plus a few hyphens and colons in the m4b filename. Libation was able to download it to "/tmp", but when copying to its final location it quickly run out of the 255 bytes/characters (as the folder name becomes very long too) enforced by the filesystem (encrypted ext4).

**Comment by rmcrackan** [comment] 2022-12-29 12:39
@wrampy

> This is more of a UI/UX issue, as a user who opens this application 1-2x a month I don't know about all these hidden features.

Yes and no. You're absolutely right that you shouldn't need to know all the nooks and crannies in order to get this to work. The part that isn't UI is: these were marked as 'pdf downloaded' when the file wasn't actually downloaded -- that sounds like a deeper bug than UI. Which ties into what Mbucari said "File names longer than Max path should be truncated, so books failing to download because of file name length is a Libation bug"

> recommend to extend the batch download status change functionality for PDFs

Agreed. I always kinda wondered if I should do this then I forgot about it. Guess I should have. Oops

@Mbucari

> ext4

Does your long file name support look for max length through environmental stuff? Or do we make assumptions based on windows?

> I think at one point libation did have an option to set PDF statuses on all visible books, and I'm not sure what happened to it

I don't believe so. This doesn't sound like something we would have removed.

> File names longer than Max path should be truncated, so books failing to download because of file name length is a Libation bug. I'll look into it more tomorrow.

This was my thought also. Lemme know what you find

**Comment by rmcrackan** [comment] 2022-12-29 14:34
> batch download status change functionality for PDFs

Done. This feature will be included in the next version

**Comment by rmcrackan** [comment] 2022-12-30 16:06
Unix file path issue will be included in the next version. Another thanks to @Mbucari for debugging this clusterf\*\*k

**Closed by rmcrackan** 2022-12-30 16:06 UTC
Labels: bug
