### ISSUE TITLE
cannot add pre-amazon audible uk account

### ISSUE THREAD

**Issue by jadekitten** [rmcrackan/Libation#171] opened 2021-12-05 22:21 UTC
[Log202112.log](https://github.com/rmcrackan/Libation/files/7656928/Log202112.log)

**Comment by rmcrackan** [comment] 2021-12-05 22:24
Thanks for the log. I'm closing this as a duplicate of #163 . I'll post progress there if I'm able to fix this.

**Closed by rmcrackan** 2021-12-05 22:24 UTC
Labels: duplicate

**Comment by jadekitten** [comment] 2021-12-05 22:54
In case it helps to know; I WAS able to import from a US pre-amazon-account.

**Comment by rmcrackan** [comment] 2021-12-06 13:11
Thank you, I have no us pre-amazon acct so that is definitely helpful to know. And also adds to the mystery. There's just a few settings that I have to tweak with US pre vs post amazon accounts. For some reason, the same changes, when applied to UK, isn't working.

**Comment by rmcrackan** [comment] 2021-12-06 14:27
FYI: I may have found a solution. Follow #163 for progress. I'll update it today or tomorrow

**Comment by rmcrackan** [comment] 2021-12-06 18:20
Fixed in latest version [v6.6](https://github.com/rmcrackan/Libation/releases/latest)
