### ISSUE TITLE
nEEDING hELP BUT NOT TOO COMPUTER SAVY

### ISSUE THREAD

**Issue by aLEKsITH1** [rmcrackan/Libation#117] opened 2021-09-16 06:44 UTC
[Log202109_023.log](https://github.com/rmcrackan/Libation/files/7175449/Log202109_023.log)
[Log202109_024.log](https://github.com/rmcrackan/Libation/files/7175450/Log202109_024.log)
[Log202109_025.log](https://github.com/rmcrackan/Libation/files/7175451/Log202109_025.log)
[Log202109_026.log](https://github.com/rmcrackan/Libation/files/7175446/Log202109_026.log)
[Log202109_027.log](https://github.com/rmcrackan/Libation/files/7175454/Log202109_027.log)
[Log202109_028.log](https://github.com/rmcrackan/Libation/files/7175455/Log202109_028.log)
[Log202109_029.log](https://github.com/rmcrackan/Libation/files/7175456/Log202109_029.log)
[Log202109_030.log](https://github.com/rmcrackan/Libation/files/7175457/Log202109_030.log)
[Log202109_031.log](https://github.com/rmcrackan/Libation/files/7175458/Log202109_031.log)
[Log202109_032.log](https://github.com/rmcrackan/Libation/files/7175461/Log202109_032.log)
(https://github.com/rmcrackan/Libation/files/7175408/Log202109_005.log)
[Log202109_006.log](https://github.com/rmcrackan/Libation/files/7175409/Log202109_006.log)
[Log202109_007.log](https://github.com/rmcrackan/Libation/files/7175411/Log202109_007.log)
[Log202109_008.log](https://github.com/rmcrackan/Libation/files/7175415/Log202109_008.log)
[Log202109_009.log](https://github.com/rmcrackan/Libation/files/7175416/Log202109_009.log)
[Log202109_010.log](https://github.com/rmcrackan/Libation/files/7175417/Log202109_010.log)
[Log202109_011.log](https://github.com/rmcrackan/Libation/files/7175418/Log202109_011.log)
[Log202109_012.log](https://github.com/rmcrackan/Libation/files/7175419/Log202109_012.log)
[Log202109_013.log](https://github.com/rmcrackan/Libation/files/7175421/Log202109_013.log)
[Log202109_033.log](https://github.com/rmcrackan/Libation/files/7175422/Log202109_033.log)
[Log202109_034.log](https://github.com/rmcrackan/Libation/files/7175423/Log202109_034.log)
[Log202109_035.log](https://github.com/rmcrackan/Libation/files/7175425/Log202109_035.log)
[Log202109_014.log](https://github.com/rmcrackan/Libation/files/7175427/Log202109_014.log)
[Log202109_015.log](https://github.com/rmcrackan/Libation/files/7175428/Log202109_015.log)
[Log202109_016.log](https://github.com/rmcrackan/Libation/files/7175429/Log202109_016.log)
[Log202109_017.log](https://github.com/rmcrackan/Libation/files/7175431/Log202109_017.log)
[Log202109_018.log](https://github.com/rmcrackan/Libation/files/7175432/Log202109_018.log)
[Log202109_019.log](https://github.com/rmcrackan/Libation/files/7175433/Log202109_019.log)
[Log202109_020.log](https://github.com/rmcrackan/Libation/files/7175434/Log202109_020.log)
nEEDING hELP BUT NOT TOO SAVY

**Comment by aLEKsITH1** [comment] 2021-09-16 06:46
Hello there guys. Thi is my first time with this website andthe Libation Software. I need some guidance I have 3 annual accoubts on audible and I'm having issues during the initial importation process.
Please take a look.
Best 
A. Gold

**Comment by rmcrackan** [comment] 2021-09-16 12:12
Duplicate of #118

**Comment by rmcrackan** [comment] 2021-09-16 12:13
Thanks for the log files. I'll take a look.

**Closed by rmcrackan** 2021-09-16 12:12 UTC

**Comment by rmcrackan** [comment] 2021-09-20 19:50
New login method available which should fix all current log in issues. See latest release [v6.0.1](https://github.com/rmcrackan/Libation/releases/tag/v6.0.1). Thank you all for your patience while I worked to fix these.
