### ISSUE TITLE
keeps crashing

### ISSUE THREAD

**Issue by LadyJaneBrown** [rmcrackan/Libation#299] opened 2022-06-25 23:23 UTC
Hi I love the idea of the program but everytime I try and download a book. it closes. please find attached my log fil
[Log202206_002.log](https://github.com/rmcrackan/Libation/files/8985715/Log202206_002.log)
e

**Comment by Mbucari** [comment] 2022-06-26 03:45
Let me guess, you are set up to download your books as MP3s, split into chapters? If so, we've found the bug and just waiting on @rmcrackan to accept some changes and publish a release. Sorry, this was a really difficult bug to find!

**Comment by rmcrackan** [comment] 2022-06-26 16:41
Duplicate of #294

**Comment by rmcrackan** [comment] 2022-06-26 16:42
I'm so sorry about this bug. A fix is going out very soon. In the meantime, I'm tracking this issue in #294

**Closed by rmcrackan** 2022-06-26 16:42 UTC
