### ISSUE TITLE
ReplacementCharacters in config file has wrong replacement strings

### ISSUE THREAD

**Issue by Deanosim** [rmcrackan/Libation#359] opened 2022-08-14 20:21 UTC
**Describe the bug**
ReplacementCharacters in config file has wrong replacement strings

**To Reproduce**

In Settings.json under "ReplacementCharacters"
For instance the Colon replacement on line 64
```json
      {
        "CharacterToReplace": ":",
        "ReplacementString": ":",
        "Description": "Colon"
      },
```
That just replaces : with : and on Windows that's an invalid character that you can't use in file and folder names, now it still sets the file and folder names to that but if you try to batch rename them or put them onto a SMB share it causes weird problems.

Personally I'd change it to this
```json      
      {
        "CharacterToReplace": ":",
        "ReplacementString": "_",
        "Description": "Colon"
      },
```
I tested that change in my config and it worked when downloading audiobooks with : in the title
So `Star Wars: Ahsoka` becomes `Star Wars_ Ahsoka` naturally it can be any other valid character.

**Comment by Deanosim** [comment] 2022-08-14 20:27
Now looking at it, this is probably the same problem as issue #357

**Comment by Mbucari** [comment] 2022-08-15 20:40
I guarantee you Libation is not trying to create a file with a colon in the filename. By default it replaces colons with `꞉` ([Modifier Letter colon](https://graphemica.com/%EA%9E%89)). Even if you have a colon as the replacement string in your settings file, Libation checks the replacement text when loading the settings and will not use an illegal path character.

You can edit this behavior in Libation Classic, but we haven't yet added an editor for this setting in Chardonnay.

**Comment by rmcrackan** [comment] 2022-08-16 11:04
Duplicate of #357

**Closed by rmcrackan** 2022-08-16 11:04 UTC
Labels: bug
