### ISSUE TITLE
Feature Request: Full Sized Images

### ISSUE THREAD

**Issue by TomboAhi** [rmcrackan/Libation#188] opened 2022-01-19 03:19 UTC
I would like an option that would allow for downloading and saving a full sized cover image, that would be placed in the folder with the completed download, as well as being named the same way as the file or have an option to format the name.

Thanks!

**Comment by rmcrackan** [comment] 2022-04-30 12:41
Duplicate of #182

**Closed by rmcrackan** 2022-04-30 12:41 UTC
Labels: enhancement
