### ISSUE TITLE
Error importing library

### ISSUE THREAD

**Issue by cYCL157** [rmcrackan/Libation#20] opened 2020-12-27 18:30 UTC
After getting the password, catcha and approval prompt successfully approving the login on my iphone, i get an error dialog that says "Error import library".  I have tried 4 times, including after having restarted the application and get the same thing.  Is there some additional information i can provide? 

US locale, 4.1.8 Libation downloaded today.

Thanks!

**Comment by rmcrackan** [comment] 2020-12-27 21:57
Sorry to hear that. Can you put your log on pastebin or attach it here?

**Comment by cYCL157** [comment] 2020-12-28 00:33
2020-12-27 11:04:57.433 -07:00 [INF] (at LibationLauncher.Program.logStartupState()) Begin Libation. {"Version":"4.1.8.2","LibationFiles":"C:\\Apps\\Libation\\LibationFiles","BooksDirectory":"C:\\Apps\\Libation","DownloadsInProgressEnum":"WinTemp","DownloadsInProgressDir":"C:\\Users\\Cort\\AppData\\Local\\Temp\\Libation\\DownloadsInProgress","DownloadsInProgressFiles":0,"DownloadsFinal":"C:\\Apps\\Libation\\LibationFiles\\DownloadsFinal","DownloadsFinalFiles":0,"DecryptInProgressEnum":"WinTemp","DecryptInProgressDir":"C:\\Users\\Cort\\AppData\\Local\\Temp\\Libation\\DecryptInProgress","DecryptInProgressFiles":0}
2020-12-27 11:04:58.933 -07:00 [INF] (at LibationWinForms.Form1.setBookBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"fullyBackedUp":0,"downloadedOnly":0,"noProgress":0,"pending":0,"statusStripText":"No books. Begin by importing your library","menuItemText":"All books have been liberated"}
2020-12-27 11:04:58.940 -07:00 [INF] (at LibationWinForms.Form1.setPdfBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"downloaded":0,"notDownloaded":0,"statusStripText":"","menuItemText":"All PDFs have been downloaded"}
2020-12-27 11:05:46.270 -07:00 [INF] (at InternalUtilities.AudibleApiActions.GetApiAsync(AudibleApi.ILoginCallback, InternalUtilities.Account)) GetApiAsync. {"Account":"AccountId=c[...]t@e[...]r.n[...]t|AccountName=c[...]t@e[...]r.n[...]s|Locale=us","LocaleName":"us"}
2020-12-27 11:06:06.152 -07:00 [INF] (at AudibleApi.Authentication.LoginResultRunner+<makeRequestAsync>d__4.MoveNext()) Redirecting to https://www.amazon.com/ap/challenge?ie=UTF8&arb=732b7a67-9563-479f-bf33-ea7a767131e1
2020-12-27 11:06:06.469 -07:00 [INF] (at AudibleApi.Authentication.LoginResultRunner+<makeRequestAsync>d__4.MoveNext()) Redirecting to https://www.amazon.com/ap/cvf/approval?arb=52d132e8-42ec-4caa-a6e4-3fe5f19372a3&openid.assoc_handle=amzn_audible_ios_us&pageId=amzn_audible_ios&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fsignin%3Fie%3DUTF8%26clientContext%3D134-2256180-9946941%26openid.pape.max_auth_age%3D0%26use_global_authentication%3Dfalse%26forceMobileLayout%3Dtrue%26accountStatusPolicy%3DP1%26openid.identity%3Dhttp%253A%252F%252Fspecs.openid.net%252Fauth%252F2.0%252Fidentifier_select%26use_audio_captcha%3Dfalse%26marketPlaceId%3DAF2M0KC94RCEA%26language%3Den-US%26pageId%3Damzn_audible_ios%26arb%3Dc771d3a0-64f9-4a80-97dc-2abff83147ef%26openid.return_to%3Dhttps%253A%252F%252Fwww.amazon.com%252Fap%252Fmaplanding%26openid.assoc_handle%3Damzn_audible_ios_us%26openid.oa2.response_type%3Dtoken%26openid.mode%3Dcheckid_setup%26openid.ns.pape%3Dhttp%253A%252F%252Fspecs.openid.net%252Fextensions%252Fpape%252F1.0%26openid.ns.oa2%3Dhttp%253A%252F%252Fwww.amazon.com%252Fap%252Fext%252Foauth%252F2%26openid.oa2.scope%3Ddevice_auth_access%26openid.claimed_id%3Dhttp%253A%252F%252Fspecs.openid.net%252Fauth%252F2.0%252Fidentifier_select%26openid.oa2.client_id%3Ddevice%253A6a52316c62706d53427a5735505a76477a45375959566674327959465a6374424a53497069546d45234132435a4a5a474c4b324a4a564d%26openid.ns%3Dhttp%253A%252F%252Fspecs.openid.net%252Fauth%252F2.0
2020-12-27 11:06:27.934 -07:00 [ERR] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__0.MoveNext()) Error importing library
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at AudibleApi.Authentication.LoginResultRunner.makeRequestAsync(Authenticate authenticate, HttpMethod method, Uri uri, HttpContent content) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 152
   at AudibleApi.Authentication.LoginResultRunner.GetResultsPageAsync(Authenticate authenticate, String url) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 22
   at AudibleApi.EzApiCreator.loginAsync(Locale locale, ILoginCallback responder) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 89
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath, ILoginCallback loginCallback) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 47
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\UNTESTED\LibraryCommands.cs:line 68
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\UNTESTED\LibraryCommands.cs:line 23
2020-12-27 11:06:27.946 -07:00 [ERR] (at LibationWinForms.Dialogs.IndexLibraryDialog+<IndexLibraryDialog_Shown>d__12.MoveNext()) Error importing library. Please try again. If this still happens after 2 or 3 tries, stop and contact administrator
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at AudibleApi.Authentication.LoginResultRunner.makeRequestAsync(Authenticate authenticate, HttpMethod method, Uri uri, HttpContent content) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 152
   at AudibleApi.Authentication.LoginResultRunner.GetResultsPageAsync(Authenticate authenticate, String url) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 22
   at AudibleApi.EzApiCreator.loginAsync(Locale locale, ILoginCallback responder) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 89
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath, ILoginCallback loginCallback) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 47
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\UNTESTED\LibraryCommands.cs:line 68
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\UNTESTED\LibraryCommands.cs:line 23
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\UNTESTED\Dialogs\IndexLibraryDialog.cs:line 34
2020-12-27 11:06:36.182 -07:00 [INF] (at InternalUtilities.AudibleApiActions.GetApiAsync(AudibleApi.ILoginCallback, InternalUtilities.Account)) GetApiAsync. {"Account":"AccountId=c[...]t@e[...]r.n[...]t|AccountName=c[...]t@e[...]r.n[...]s|Locale=us","LocaleName":"us"}
2020-12-27 11:07:28.899 -07:00 [INF] (at AudibleApi.Authentication.LoginResultRunner+<makeRequestAsync>d__4.MoveNext()) Redirecting to https://www.amazon.com/ap/challenge?ie=UTF8&arb=9a3b5c76-4f1f-4db5-9dc3-20ddd5804fa9
2020-12-27 11:07:29.218 -07:00 [INF] (at AudibleApi.Authentication.LoginResultRunner+<makeRequestAsync>d__4.MoveNext()) Redirecting to https://www.amazon.com/ap/cvf/approval?arb=1d8136fa-29c2-48df-b326-abf001c70ea1&openid.assoc_handle=amzn_audible_ios_us&pageId=amzn_audible_ios&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fsignin%3Fie%3DUTF8%26clientContext%3D133-5397400-6477956%26openid.pape.max_auth_age%3D0%26use_global_authentication%3Dfalse%26forceMobileLayout%3Dtrue%26accountStatusPolicy%3DP1%26openid.identity%3Dhttp%253A%252F%252Fspecs.openid.net%252Fauth%252F2.0%252Fidentifier_select%26use_audio_captcha%3Dfalse%26marketPlaceId%3DAF2M0KC94RCEA%26language%3Den-US%26pageId%3Damzn_audible_ios%26arb%3D5b5cd7f0-09e3-453b-a2b7-40d7f3e45e2a%26openid.return_to%3Dhttps%253A%252F%252Fwww.amazon.com%252Fap%252Fmaplanding%26openid.assoc_handle%3Damzn_audible_ios_us%26openid.oa2.response_type%3Dtoken%26openid.mode%3Dcheckid_setup%26openid.ns.pape%3Dhttp%253A%252F%252Fspecs.openid.net%252Fextensions%252Fpape%252F1.0%26openid.ns.oa2%3Dhttp%253A%252F%252Fwww.amazon.com%252Fap%252Fext%252Foauth%252F2%26openid.oa2.scope%3Ddevice_auth_access%26openid.claimed_id%3Dhttp%253A%252F%252Fspecs.openid.net%252Fauth%252F2.0%252Fidentifier_select%26openid.oa2.client_id%3Ddevice%253A6a52316c62706d53427a5735505a76477a45375959566674327959465a6374424a53497069546d45234132435a4a5a474c4b324a4a564d%26openid.ns%3Dhttp%253A%252F%252Fspecs.openid.net%252Fauth%252F2.0
2020-12-27 11:07:39.570 -07:00 [ERR] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__0.MoveNext()) Error importing library
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at AudibleApi.Authentication.LoginResultRunner.makeRequestAsync(Authenticate authenticate, HttpMethod method, Uri uri, HttpContent content) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 152
   at AudibleApi.Authentication.LoginResultRunner.GetResultsPageAsync(Authenticate authenticate, String url) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 22
   at AudibleApi.EzApiCreator.loginAsync(Locale locale, ILoginCallback responder) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 89
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath, ILoginCallback loginCallback) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 47
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\UNTESTED\LibraryCommands.cs:line 68
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\UNTESTED\LibraryCommands.cs:line 23
2020-12-27 11:07:39.578 -07:00 [ERR] (at LibationWinForms.Dialogs.IndexLibraryDialog+<IndexLibraryDialog_Shown>d__12.MoveNext()) Error importing library. Please try again. If this still happens after 2 or 3 tries, stop and contact administrator
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at AudibleApi.Authentication.LoginResultRunner.makeRequestAsync(Authenticate authenticate, HttpMethod method, Uri uri, HttpContent content) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 152
   at AudibleApi.Authentication.LoginResultRunner.GetResultsPageAsync(Authenticate authenticate, String url) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 22
   at AudibleApi.EzApiCreator.loginAsync(Locale locale, ILoginCallback responder) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 89
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath, ILoginCallback loginCallback) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 47
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\UNTESTED\LibraryCommands.cs:line 68
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\UNTESTED\LibraryCommands.cs:line 23
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\UNTESTED\Dialogs\IndexLibraryDialog.cs:line 34
2020-12-27 11:08:03.443 -07:00 [INF] (at LibationLauncher.Program.logStartupState()) Begin Libation. {"Version":"4.1.8.2","LibationFiles":"C:\\Apps\\Libation\\LibationFiles","BooksDirectory":"C:\\Apps\\Libation","DownloadsInProgressEnum":"WinTemp","DownloadsInProgressDir":"C:\\Users\\Cort\\AppData\\Local\\Temp\\Libation\\DownloadsInProgress","DownloadsInProgressFiles":0,"DownloadsFinal":"C:\\Apps\\Libation\\LibationFiles\\DownloadsFinal","DownloadsFinalFiles":0,"DecryptInProgressEnum":"WinTemp","DecryptInProgressDir":"C:\\Users\\Cort\\AppData\\Local\\Temp\\Libation\\DecryptInProgress","DecryptInProgressFiles":0}
2020-12-27 11:08:04.359 -07:00 [INF] (at LibationWinForms.Form1.setBookBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"fullyBackedUp":0,"downloadedOnly":0,"noProgress":0,"pending":0,"statusStripText":"No books. Begin by importing your library","menuItemText":"All books have been liberated"}
2020-12-27 11:08:04.367 -07:00 [INF] (at LibationWinForms.Form1.setPdfBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"downloaded":0,"notDownloaded":0,"statusStripText":"","menuItemText":"All PDFs have been downloaded"}
2020-12-27 11:08:08.574 -07:00 [INF] (at InternalUtilities.AudibleApiActions.GetApiAsync(AudibleApi.ILoginCallback, InternalUtilities.Account)) GetApiAsync. {"Account":"AccountId=c[...]t@e[...]r.n[...]t|AccountName=c[...]t@e[...]r.n[...]s|Locale=us","LocaleName":"us"}
2020-12-27 11:08:30.388 -07:00 [INF] (at AudibleApi.Authentication.LoginResultRunner+<makeRequestAsync>d__4.MoveNext()) Redirecting to https://www.amazon.com/ap/challenge?ie=UTF8&arb=ff4b75db-c275-49e5-bfac-da6424793a2f
2020-12-27 11:08:30.707 -07:00 [INF] (at AudibleApi.Authentication.LoginResultRunner+<makeRequestAsync>d__4.MoveNext()) Redirecting to https://www.amazon.com/ap/cvf/approval?arb=e1cdb52f-540d-4cf3-893b-98ff4e0140ed&openid.assoc_handle=amzn_audible_ios_us&pageId=amzn_audible_ios&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fsignin%3Fie%3DUTF8%26clientContext%3D134-7395337-1393245%26openid.pape.max_auth_age%3D0%26use_global_authentication%3Dfalse%26forceMobileLayout%3Dtrue%26accountStatusPolicy%3DP1%26openid.identity%3Dhttp%253A%252F%252Fspecs.openid.net%252Fauth%252F2.0%252Fidentifier_select%26use_audio_captcha%3Dfalse%26marketPlaceId%3DAF2M0KC94RCEA%26language%3Den-US%26pageId%3Damzn_audible_ios%26arb%3D504a0aad-f4c1-48ea-befc-333620766112%26openid.return_to%3Dhttps%253A%252F%252Fwww.amazon.com%252Fap%252Fmaplanding%26openid.assoc_handle%3Damzn_audible_ios_us%26openid.oa2.response_type%3Dtoken%26openid.mode%3Dcheckid_setup%26openid.ns.pape%3Dhttp%253A%252F%252Fspecs.openid.net%252Fextensions%252Fpape%252F1.0%26openid.ns.oa2%3Dhttp%253A%252F%252Fwww.amazon.com%252Fap%252Fext%252Foauth%252F2%26openid.oa2.scope%3Ddevice_auth_access%26openid.claimed_id%3Dhttp%253A%252F%252Fspecs.openid.net%252Fauth%252F2.0%252Fidentifier_select%26openid.oa2.client_id%3Ddevice%253A6a52316c62706d53427a5735505a76477a45375959566674327959465a6374424a53497069546d45234132435a4a5a474c4b324a4a564d%26openid.ns%3Dhttp%253A%252F%252Fspecs.openid.net%252Fauth%252F2.0
2020-12-27 11:08:39.915 -07:00 [ERR] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__0.MoveNext()) Error importing library
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at AudibleApi.Authentication.LoginResultRunner.makeRequestAsync(Authenticate authenticate, HttpMethod method, Uri uri, HttpContent content) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 152
   at AudibleApi.Authentication.LoginResultRunner.GetResultsPageAsync(Authenticate authenticate, String url) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 22
   at AudibleApi.EzApiCreator.loginAsync(Locale locale, ILoginCallback responder) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 89
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath, ILoginCallback loginCallback) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 47
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\UNTESTED\LibraryCommands.cs:line 68
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\UNTESTED\LibraryCommands.cs:line 23
2020-12-27 11:08:39.926 -07:00 [ERR] (at LibationWinForms.Dialogs.IndexLibraryDialog+<IndexLibraryDialog_Shown>d__12.MoveNext()) Error importing library. Please try again. If this still happens after 2 or 3 tries, stop and contact administrator
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at AudibleApi.Authentication.LoginResultRunner.makeRequestAsync(Authenticate authenticate, HttpMethod method, Uri uri, HttpContent content) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 152
   at AudibleApi.Authentication.LoginResultRunner.GetResultsPageAsync(Authenticate authenticate, String url) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 22
   at AudibleApi.EzApiCreator.loginAsync(Locale locale, ILoginCallback responder) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 89
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath, ILoginCallback loginCallback) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 47
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\UNTESTED\LibraryCommands.cs:line 68
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\UNTESTED\LibraryCommands.cs:line 23
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\UNTESTED\Dialogs\IndexLibraryDialog.cs:line 34
2020-12-27 11:26:46.762 -07:00 [INF] (at LibationLauncher.Program.logStartupState()) Begin Libation. {"Version":"4.1.8.2","LibationFiles":"C:\\Apps\\Libation\\LibationFiles","BooksDirectory":"C:\\Apps\\Libation","DownloadsInProgressEnum":"WinTemp","DownloadsInProgressDir":"C:\\Users\\Cort\\AppData\\Local\\Temp\\Libation\\DownloadsInProgress","DownloadsInProgressFiles":0,"DownloadsFinal":"C:\\Apps\\Libation\\LibationFiles\\DownloadsFinal","DownloadsFinalFiles":0,"DecryptInProgressEnum":"WinTemp","DecryptInProgressDir":"C:\\Users\\Cort\\AppData\\Local\\Temp\\Libation\\DecryptInProgress","DecryptInProgressFiles":0}
2020-12-27 11:26:47.718 -07:00 [INF] (at LibationWinForms.Form1.setBookBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"fullyBackedUp":0,"downloadedOnly":0,"noProgress":0,"pending":0,"statusStripText":"No books. Begin by importing your library","menuItemText":"All books have been liberated"}
2020-12-27 11:26:47.726 -07:00 [INF] (at LibationWinForms.Form1.setPdfBackupCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.Book, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"downloaded":0,"notDownloaded":0,"statusStripText":"","menuItemText":"All PDFs have been downloaded"}
2020-12-27 11:26:50.392 -07:00 [INF] (at InternalUtilities.AudibleApiActions.GetApiAsync(AudibleApi.ILoginCallback, InternalUtilities.Account)) GetApiAsync. {"Account":"AccountId=c[...]t@e[...]r.n[...]t|AccountName=c[...]t@e[...]r.n[...]s|Locale=us","LocaleName":"us"}
2020-12-27 11:27:09.226 -07:00 [INF] (at AudibleApi.Authentication.LoginResultRunner+<makeRequestAsync>d__4.MoveNext()) Redirecting to https://www.amazon.com/ap/challenge?ie=UTF8&arb=a93f6aa5-f564-4de2-adcd-0b94554b3d79
2020-12-27 11:27:09.537 -07:00 [INF] (at AudibleApi.Authentication.LoginResultRunner+<makeRequestAsync>d__4.MoveNext()) Redirecting to https://www.amazon.com/ap/cvf/approval?arb=ab15c648-568e-49a0-b997-cb0b180ef87d&openid.assoc_handle=amzn_audible_ios_us&pageId=amzn_audible_ios&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fap%2Fsignin%3Fie%3DUTF8%26clientContext%3D130-3936857-9485057%26openid.pape.max_auth_age%3D0%26use_global_authentication%3Dfalse%26forceMobileLayout%3Dtrue%26accountStatusPolicy%3DP1%26openid.identity%3Dhttp%253A%252F%252Fspecs.openid.net%252Fauth%252F2.0%252Fidentifier_select%26use_audio_captcha%3Dfalse%26marketPlaceId%3DAF2M0KC94RCEA%26language%3Den-US%26pageId%3Damzn_audible_ios%26arb%3Dd852df16-151e-4cd9-956c-87d5de0fa8cb%26openid.return_to%3Dhttps%253A%252F%252Fwww.amazon.com%252Fap%252Fmaplanding%26openid.assoc_handle%3Damzn_audible_ios_us%26openid.oa2.response_type%3Dtoken%26openid.mode%3Dcheckid_setup%26openid.ns.pape%3Dhttp%253A%252F%252Fspecs.openid.net%252Fextensions%252Fpape%252F1.0%26openid.ns.oa2%3Dhttp%253A%252F%252Fwww.amazon.com%252Fap%252Fext%252Foauth%252F2%26openid.oa2.scope%3Ddevice_auth_access%26openid.claimed_id%3Dhttp%253A%252F%252Fspecs.openid.net%252Fauth%252F2.0%252Fidentifier_select%26openid.oa2.client_id%3Ddevice%253A6a52316c62706d53427a5735505a76477a45375959566674327959465a6374424a53497069546d45234132435a4a5a474c4b324a4a564d%26openid.ns%3Dhttp%253A%252F%252Fspecs.openid.net%252Fauth%252F2.0
2020-12-27 11:27:17.343 -07:00 [ERR] (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__0.MoveNext()) Error importing library
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at AudibleApi.Authentication.LoginResultRunner.makeRequestAsync(Authenticate authenticate, HttpMethod method, Uri uri, HttpContent content) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 152
   at AudibleApi.Authentication.LoginResultRunner.GetResultsPageAsync(Authenticate authenticate, String url) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 22
   at AudibleApi.EzApiCreator.loginAsync(Locale locale, ILoginCallback responder) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 89
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath, ILoginCallback loginCallback) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 47
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\UNTESTED\LibraryCommands.cs:line 68
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\UNTESTED\LibraryCommands.cs:line 23
2020-12-27 11:27:17.355 -07:00 [ERR] (at LibationWinForms.Dialogs.IndexLibraryDialog+<IndexLibraryDialog_Shown>d__12.MoveNext()) Error importing library. Please try again. If this still happens after 2 or 3 tries, stop and contact administrator
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at AudibleApi.Authentication.LoginResultRunner.makeRequestAsync(Authenticate authenticate, HttpMethod method, Uri uri, HttpContent content) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 152
   at AudibleApi.Authentication.LoginResultRunner.GetResultsPageAsync(Authenticate authenticate, String url) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\LoginResultRunner.cs:line 22
   at AudibleApi.EzApiCreator.loginAsync(Locale locale, ILoginCallback responder) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 89
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath, ILoginCallback loginCallback) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 47
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\UNTESTED\LibraryCommands.cs:line 68
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\UNTESTED\LibraryCommands.cs:line 23
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\UNTESTED\Dialogs\IndexLibraryDialog.cs:line 34

**Comment by rmcrackan** [comment] 2020-12-28 16:19
Sorry to say that this 404/CVF issue is one that I haven't yet cracked. The issue is being revisited periodically in another issue. I'm closing this issue and any progress will be reported in #16

**Closed by rmcrackan** 2020-12-28 16:19 UTC
