### ISSUE TITLE
v11.3.9 gives an error whenever I try to navigate it using the tab & arrow keys.

### ISSUE THREAD

**Issue by casualfan** [rmcrackan/Libation#904] opened 2024-05-12 19:17 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**

[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]

**Log Files**
Attach your Libation log file here.
The owning DataGridViewCell object has not been set.

   at System.Windows.Forms.DataGridViewCell.DataGridViewCellAccessibleObject.get_ParentPrivate()
   at System.Windows.Forms.DataGridViewCell.DataGridViewCellAccessibleObject.get_Bounds()
   at System.Windows.Forms.DataGridViewCell.System.Windows.Forms.IKeyboardToolTip.GetNeighboringToolsRectangles()
   at System.Windows.Forms.ToolTip.GetOptimalToolTipPosition(IKeyboardToolTip tool, Rectangle toolRectangle, Int32 width, Int32 height)
   at System.Windows.Forms.ToolTip.ShowKeyboardToolTip(String text, IKeyboardToolTip tool, Int32 duration)
   at System.Windows.Forms.KeyboardToolTipStateMachine.ShowToolTip(IKeyboardToolTip tool, ToolTip toolTip)
   at System.Windows.Forms.KeyboardToolTipStateMachine.Transition(IKeyboardToolTip tool, ToolTip tooltip, SmEvent event)
   at System.Windows.Forms.KeyboardToolTipStateMachine.Transit(SmEvent event, IKeyboardToolTip source)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

**Comment by rmcrackan** [comment] 2024-05-13 12:36
Thanks for the bug report. This looks related to a piece of code I touched recently so I assume I created a bug. I'm not able to make this happen on my computer though. Can you attach your latest log file? You can find it here: Libation > Settings > click "Open log folder"

**Comment by casualfan** [comment] 2024-05-13 14:56
is it a zip file?

**Comment by casualfan** [comment] 2024-05-13 15:09
[_Log202405.zip](https://github.com/rmcrackan/Libation/files/15296551/_Log202405.zip)

**Comment by rmcrackan** [comment] 2024-05-13 17:47
This is disturbing. I can't make it happen for me no matter what I do but I see in your logs that it happened to you 3 times within a few seconds. Has it happened again since then?

**Comment by CLHatch** [comment] 2024-05-13 17:53
> This is disturbing. I can't make it happen for me no matter what I do but I see in your logs that it happened to you 3 times within a few seconds. Has it happened again since then?

Perhaps something to do with the version of Windows being used?  I'm using Windows 11 here.  If by any chance he's on Windows 11 and you on Windows 10, might not show up on your end?

**Comment by CLHatch** [comment] 2024-05-13 17:59
I just switched to 11.3.9 Chardonnay to 11.3.9 Classic, hit the tab key a few times, and got an error myself.

**Comment by CLHatch** [comment] 2024-05-13 18:05
OK, deleted the log files and started up again, started tabbing, and the error pops up as soon as I tab to the first "stoplight".

```
The owning DataGridViewCell object has not been set.

   at System.Windows.Forms.DataGridViewCell.DataGridViewCellAccessibleObject.get_ParentPrivate()
   at System.Windows.Forms.DataGridViewCell.DataGridViewCellAccessibleObject.get_Bounds()
   at System.Windows.Forms.ToolTip.ShowKeyboardToolTip(String text, IKeyboardToolTip tool, Int32 duration)
   at System.Windows.Forms.KeyboardToolTipStateMachine.ShowToolTip(IKeyboardToolTip tool, ToolTip toolTip)
   at System.Windows.Forms.KeyboardToolTipStateMachine.Transition(IKeyboardToolTip tool, ToolTip tooltip, SmEvent event)
   at System.Windows.Forms.KeyboardToolTipStateMachine.Transit(SmEvent event, IKeyboardToolTip source)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```
[_Log202405.zip](https://github.com/rmcrackan/Libation/files/15298433/_Log202405.zip)

**Comment by rmcrackan** [comment] 2024-05-13 18:12
Thanks. You both appear to have auto-scan enabled but I don't so I turned it on and restarted. I can now force this to happen if I use my arrow keys like crazy while the initial scan is happening. This is going to be a weird one...

**Comment by CLHatch** [comment] 2024-05-13 18:16
> Thanks. You both appear to have auto-scan enabled but I don't so I turned it on and restarted. I can now force this to happen if I use my arrow keys like crazy while the initial scan is happening. This is going to be a weird one...

If you mean the top setting here...

![image](https://github.com/rmcrackan/Libation/assets/13066223/1659f56b-73b3-4c54-9cc9-2a6313ca905c)

I did have that turned on. But i just now turned that off, and still getting the same error.

**Comment by CLHatch** [comment] 2024-05-13 18:17
It also ONLY gives me an error when I tab to one of the "stoplights".

**Comment by CLHatch** [comment] 2024-05-13 18:26
https://github.com/rmcrackan/Libation/assets/13066223/01d63304-6c99-4ed2-9133-df3464c38c43

Here's a recording of it, right after starting Libation.

**Comment by rmcrackan** [comment] 2024-05-13 18:30
Thank you so much for this. This is maddening. This error will happen only for the version which is built for the public. The way I run it for debugging, this error will not occur. So I can't reproduce it in a way that can be easily debugged. This is going to be a weird one.

**Comment by CLHatch** [comment] 2024-05-13 18:32
> Thank you so much for this. This is maddening. This error will happen only for the version which is built for the public. The way I run it for debugging, this error will not occur. So I can't reproduce it in a way that can be easily debugged. This is going to be a weird one.

Oh, fun. :-D

Well, at least you know where to look.  I'm guessing something to do with the changes in the "stoplight" you did to make the text readers work in that field.

**Comment by CLHatch** [comment] 2024-05-13 18:38
> > I'm guessing something to do with the changes in the "stoplight" you did to make the text readers work in that field.
> 
> Almost certainly. No good dead goes unpunished.

Just to be sure, I rolled back to Libation Classic 11.3.8, and no error on tabbing to the stoplights.

**Comment by rmcrackan** [comment] 2024-05-13 19:44
Fixed in the latest version 11.3.11 -- https://github.com/rmcrackan/Libation/releases/tag/v11.3.11

(I know I skipped 11.3.10. The explanation is technical and utterly boring.)

Please let me know if it still gives you errors. Thank you both for your patience and help!!

**Closed by rmcrackan** 2024-05-13 19:44 UTC
Labels: bug

**Comment by CLHatch** [comment] 2024-05-13 19:46
> Fixed in the latest version 11.3.11 -- https://github.com/rmcrackan/Libation/releases/tag/v11.3.11
> 
> (I know I skipped 11.3.10. The explanation is technical and utterly boring.)
> 
> Please let me know if it still gives you errors. Thank you both for your patience and help!!

I can verify that it fixed it on my end, and Chardonnay also still working.

**Comment by rmcrackan** [comment] 2024-05-13 19:53
Thanks for checking but Chardonnay is actually untouched in these last few releases. This is Classic only.

I'd love to retrofit Chardonnay for screen readers but I just don't have it in me. I'm trying hard to keep Classic as accessible as possible though.

**Comment by CharlieRussel** [comment] 2024-05-13 19:53
Working correctly here. (But I hadn't updated for the last several, so never actually had it hit me. And yes, I'm on Classic.)

**Comment by CLHatch** [comment] 2024-05-13 19:57
> Thanks for checking but Chardonnay is actually untouched in these last few releases. This is Classic only.
> 
> I'd love to retrofit Chardonnay for screen readers but I just don't have it in me. I'm trying hard to keep Classic as accessible as possible though.

Yeah, had a feeling it was untouched, but figured best to verify the changes in Classic didn't break Chardonnay, in case there was some shared code there. :)

**Comment by rmcrackan** [comment] 2024-05-13 20:03
Good call. There's actually an enormous amount of shared code. This happens to be in the thin purely UI part, which is separate between the 2.
