### ISSUE TITLE
Move mp4 moov atom to the beginning of file

### ISSUE THREAD

**Issue by saunaants** [rmcrackan/Libation#366] opened 2022-09-03 18:31 UTC
Currently audible files have the moov atom at the end of the file and this prevents streaming or playing the files without fully downloading.

Similar feature is FFmpeg option -movflags faststart or mp4v2 "optimize" option

**Comment by rmcrackan** [comment] 2022-09-03 19:06
Thanks for the detailed analysis of this. Can you tell us a bit more about the real-world problem that this would solve? I don't try to stream my books so I'm not familiar.

While Libation does try to be as convenient as possible for the largest number of users, it isn't intended to be a full replacement for ffmpeg so I can't promise that this will be added.

**Comment by saunaants** [comment] 2022-09-04 05:03
It is useful when the mp4 file is not fully available. If the moov atom is at the beginning means you can start playback when file is only partially downloaded or when using a non-seekable medium like tape or compressed archive.

**Comment by rmcrackan** [comment] 2022-09-04 13:33
Which of these are your typical case?

**Comment by Mbucari** [comment] 2022-09-07 19:03
I've thought about doing this. It's not technically challenging, but it will be it'll take some doin'.

@rmcrackan  The problem is that the this operation requires a lot of IO. It'll be practically unnoticeable on an SSD, and it will seem like forever on a USB flash drive or network location.

**Comment by rmcrackan** [comment] 2022-12-29 16:03
@Mbucari I don't intend to add general audio file manipulation to Libation. I want to keep Libation being the best at what it is and letting other software do what they do best. If it's not specific to audiobooks or the metadata that only we have easy access to, then it probably doesn't belong here.

Exceptions:

* providing mp3s was easily the single most popular request
* I could imagine better id3 tag writing, particularly in cases of chapter-ized files. That doesn't seem easily doable after the fact by other audio file manipulation software. Audio metadata is a friggin mess though so I'm no hurry to tackle that
* when coders other than me want to take it on, I won't stop you. If you feel like doing this, go for it. If you don't intend to, please let me know and this request should be closed.

**Comment by Mbucari** [comment] 2022-12-30 00:12
> @Mbucari I don't intend to add general audio file manipulation to Libation.

I agree with this. If the user wants to relocate the moov atom to the beginning of the file, they can use FFMpeg to do it like so:

`ffmpeg -i original.m4b -movflags faststart -c copy new.m4b`

**Comment by Mbucari** [comment] 2023-01-22 05:17
I added this feature in v 0.5.5 of AAXClean. It's actually not as slow as I thought it would be. Even a 1.7GB book on a WD Blue HDD it take only about 2 seconds to do. I'll add it to Libation shortly. I tweaked the way tasks are created and cancelled and how progress is reported, so its incompatible with the previous versions.

**Comment by rmcrackan** [comment] 2023-01-22 15:27
That's really fast. Should I re-open this ticket?

**Comment by Mbucari** [comment] 2023-01-22 16:16
Yes, please do.

**Comment by rmcrackan** [comment] 2023-01-24 03:48
Fixed. Will be included in the next release

**Closed** 2023-01-24 03:48 UTC
Labels: enhancement

**Comment by rmcrackan** [comment] 2023-01-24 04:09
New version [9.1](https://github.com/rmcrackan/Libation/releases/latest) is published
