### ISSUE TITLE
Attempt to scan in 10.6.1 errors in Chardonnay

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#675] opened 2023-07-13 22:40 UTC
**Describe the bug**
Upgrading from 10.6.0 (beta) to 10.6.1 (Chardonnay) and get the following when I try to scan on one account: (NOTE: Chardonnay is on C:\LibationChard and Classic is on D:\Libation). Classic upgraded and scanned just fine.

Attempted to scan one account in 10.6.1. Instead, error message: 
Could not capture a current SynchronizationContext

   at Dinah.Core.Threading.SynchronizeInvoker..ctor()
   at LibationUiBase.GridView.EntryStatus..ctor(LibraryBook libraryBook) in D:\a\Libation\Libation\Source\LibationUiBase\GridView\EntryStatus.cs:line 71
   at LibationAvalonia.ViewModels.AvaloniaEntryStatus.Create(LibraryBook libraryBook) in D:\a\Libation\Libation\Source\LibationAvalonia\ViewModels\AvaloniaEntryStatus.cs:line 14
   at LibationUiBase.GridView.GridEntry`1.UpdateLibraryBook(LibraryBook libraryBook) in D:\a\Libation\Libation\Source\LibationUiBase\GridView\GridEntry[TStatus].cs:line 100
   at Dinah.Core.Threading.SynchronizeInvoker.ThreadMethodEntry.Complete()
   at Dinah.Core.Threading.SynchronizeInvoker.Invoke(Delegate method, Object[] args)
   at LibationUiBase.GridView.GridEntry`1.UserDefinedItem_ItemChanged(Object sender, String itemName) in D:\a\Libation\Libation\Source\LibationUiBase\GridView\GridEntry[TStatus].cs:line 161
   at DtoImporterService.BookImporter.updateBook(ImportItem importItem, Book book) in D:\a\Libation\Libation\Source\DtoImporterService\BookImporter.cs:line 186
   at DtoImporterService.BookImporter.upsertBooks(IEnumerable`1 importItems) in D:\a\Libation\Libation\Source\DtoImporterService\BookImporter.cs:line 68
   at DtoImporterService.ImporterBase`1.Run[TResult](Func`2 func, T param) in D:\a\Libation\Libation\Source\DtoImporterService\ImporterBase.cs:line 39
   at DtoImporterService.LibraryBookImporter.DoImport(IEnumerable`1 importItems) in D:\a\Libation\Libation\Source\DtoImporterService\LibraryBookImporter.cs:line 24
   at DtoImporterService.ImporterBase`1.Run[TResult](Func`2 func, T param) in D:\a\Libation\Libation\Source\DtoImporterService\ImporterBase.cs:line 39
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ApplicationServices.LibraryCommands.importIntoDbAsync(List`1 importItems) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 318
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 137
   at LibationAvalonia.ViewModels.MainVM.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\Li

**To Reproduce**

1. Go to 'Import -> Scan Library of some accounts'
2. Click on 'Select active US account
3. Click Import

**Expected behavior**
There haven't been any changes to that account since the last scan, so I expected no change in the accounts. However, on closing Chardonnay, and restarting later, no error was received and the scan completed successfully. 

**Screenshots**

**Platform**

Windows 11, Libation Chardonnay 10.6.1

**Log Files**

[LibationLog.zip](https://github.com/rmcrackan/Libation/files/12044922/LibationLog.zip)

**Comment by Mbucari** [comment] 2023-07-13 23:01
@CharlieRussel

How many times has this happened? Just once, or every time you scan your account?

Does it happen if you scan all accounts, or just when you scan one?

**Comment by CharlieRussel** [comment] 2023-07-14 01:14
Once only. I haven’t tried more than the one account.

Charlie.
(he/him/his)

Sent from Outlook<https://aka.ms/qtex0l> on my phone. Please excuse any terseness or Autocorrect typos.
________________________________

**Comment by Mbucari** [comment] 2023-07-14 01:18
@CharlieRussel That's encouraging. I tracked down the _location_ of the bug, and by rights it should be impossible for it to happen. I'll leave this open for a week or so. Please let me know if it happens again (not that I have any ideas how to fix it).

**Comment by CharlieRussel** [comment] 2023-07-14 04:24
Sorry, @Mbucari -- repro steps. Run Classic. Scan single account. (No new books found.) Close classic. Open Chardonnay. Scan that same account. 

![image](https://github.com/rmcrackan/Libation/assets/21000516/b607cc0b-0000-437f-9bf2-565d448f2881)

Obviously, this is not something I'd routinely do -- I much prefer Classic, but I've been running Chardonnay just for testing purposes. Any chance there's a file lock problem?

**Comment by Mbucari** [comment] 2023-07-14 12:39
> Any chance there's a file lock problem?

Nope. The library scan is done on a background thread. When a book is changed a notification is sent to the grid entry to update itself with the new data by calling `UpdateLibraryBook`. `UpdateLibraryBook` creates a new `EntryStatus`.

`EntryStatus` needs to be created on the UI thread so that it can capture the UI's synchronization context, so `UpdateLibraryBook` is invoked on the UI thread.

The reason I say this should be impossible is because Invoking `UpdateLibraryBook` should be sending it to the UI thread to execute, but apparently once it's executing on the UI thread there is no synchronization context for `EntryStatus` to capture. It's baffling.

--------------

I haven't been able to reproduce this on my end. Can you please do me a favor and send me your libationcontext.db as well as your library scans? To get the library scans, change your logging level to debug and do a scan. They'll be safe to a zip file in your libation settings folder. Thank you!

**Comment by CharlieRussel** [comment] 2023-07-14 17:07
Arrgghh! OK, so for the fun of it today, I tried going the other direction. I bought a book, ran Chardonnay, and it downloaded it just fine. And then I ran Classic and: 
![image](https://github.com/rmcrackan/Libation/assets/21000516/eaf1a08b-26c8-416e-8b23-adc8b186bb20)
I've attached the de
[LibationContext.zip](https://github.com/rmcrackan/Libation/files/12052435/LibationContext.zip)
bug level log file
[Log202307.zip](https://github.com/rmcrackan/Libation/files/12052424/Log202307.zip)

I'm now flummoxed. I closed Classic and restarted it again, ran the scan, and it completed normally.

**Comment by Mbucari** [comment] 2023-07-14 18:49
@CharlieRussel Can you please get me your library scans too? Go to settings and change logging level to "Debug", then do a scan. They'll be saved in a file called "LibraryScans.zip"

**Comment by Mbucari** [comment] 2023-07-14 19:11
Oh my god I think I know what's going on here.

**Comment by rmcrackan** [comment] 2023-07-14 19:14
> Oh my god I think I know what's going on here.

That got my attention. What'd you find?

**Comment by Mbucari** [comment] 2023-07-14 19:29
Every `GridEntry` and `EntryStatus` capture's the current thread's synchronization context. They need it because all property changed notifications have to be invoked on the UI thread. The way we've been doing that since going xplat is to make both `GridEntry` and `EntryStatus` inherit from [SynchronizeInvoker](https://github.com/rmcrackan/Dinah.Core/blob/master/Dinah.Core/Threading/SynchronizeInvoker.cs).

When I parallelized grid entry creation, I had a problem. The big cost of loading the library was actually instantiating the `GridEntry` objects, but If I spun up a bunch of threads to instantiate them then it couldn't capture the context. I got around this by first capturing the UI's sync context and then setting each worker thread's sync context.

https://github.com/rmcrackan/Libation/blob/cb91a591f03766fd85c7e3063090f242bcd370e2/Source/LibationUiBase/GridView/LibraryBookEntry%5BTStatus%5D.cs#L47-L55 

And here comes the problem. `SynchronizeInvoker` tries to determine if invocation is required by comparing the currently executing thread's  Managed thread ID **to the ID of the thread from which the sync context was captured**. Thread IDs are unique, but once a thread is closed its ID can be reused. So all those `GridEntry` and `EntryStatus` objects that were created on who-knows how many worker threads captured the worker threads' IDs. Then, new worker threads are started for the library scan. Some of the IDs are reused. And depending on luck, some of the Invoke calls incorrectly determine that invocation is not required and so it tries to execute on the current thread, screwing the pooch.

**Comment by CharlieRussel** [comment] 2023-07-14 19:50
Hunh -- I think you might have it, @Mbucari. I know dealing with parallelization can be tricky, and it sounds like you might have identified the source. Not sure if you still need it, but I can't upload LibraryScans.zip -- it's too big. (48Mb) Do you want it to your email? Or up on my OneDrive and I'll send you a link?

**Comment by Mbucari** [comment] 2023-07-14 19:54
> Not sure if you still need it, but I can't upload LibraryScans.zip -- it's too big. (48Mb) Do you want it to your email? Or up on my OneDrive and I'll send you a link?

Please do. I haven't been able to replicate this bug yet because one of the factors increasing the probability of this error is how many books already in the DB have **changed** (not merely added or deleted).

So I think you have quite a few changes incoming and if I'm able to simulate your library scan I should be able to trigger this error and verify that's what's happening.

OneDrive link works perfectly for me.

**Comment by CharlieRussel** [comment] 2023-07-14 19:55
Sent

**Comment by Mbucari** [comment] 2023-07-14 20:30
@CharlieRussel got em

Can you tell me how many cores your CPU has?

**Comment by CharlieRussel** [comment] 2023-07-14 22:07
msinfo32 reports 4 cores, 8 logical processors. (Hey, it's only a laptop after all :) )

**Comment by rmcrackan** [comment] 2023-07-15 01:30
Fixed (hopefully) in (version 10.6.2)[https://github.com/rmcrackan/Libation/releases/latest]

**Comment by rmcrackan** [comment] 2023-07-15 01:31
Thank you @CharlieRussel for all of your help!

**Closed by rmcrackan** 2023-07-15 01:30 UTC
Labels: bug

**Comment by CharlieRussel** [comment] 2023-07-15 01:40
@rmcrackan and @Mbucari No, thank you, for a great program!

**Comment by Mbucari** [comment] 2023-07-15 01:47
@CharlieRussel you must welcome, and yes thank you for the help!

Can you verify that everything is working correctly and 10.6.2? I'm positive I fixed it, but confirmation is always nice!

**Comment by CharlieRussel** [comment] 2023-07-15 01:51
Yup. After dinner I’ll sit down and try to break it. ;)

Charlie.
(he/him/his)

Sent from Outlook<https://aka.ms/qtex0l> on my phone. Please excuse any terseness or Autocorrect typos.
________________________________

**Comment by CharlieRussel** [comment] 2023-07-15 03:42
> @CharlieRussel you're most welcome, and yes thank you for the help!
> 
> Can you verify that everything is working correctly and 10.6.2? I'm positive I fixed it, but confirmation is always nice!

@Mbucari -- well, so far so good. It didn't fail tonight over several tries. So looking good.
