### ISSUE TITLE
Warn user if an owned book is removed from their audible library

### ISSUE THREAD

**Issue by Zachman1** [rmcrackan/Libation#204] opened 2022-03-03 01:13 UTC
Audible has a tendency to remove books from their website for quality issues. The book may or may not be also removed from their library. If an owned book is removed from the library, it would be a useful feature if Libation could alert users of this. This functionality should not warn users if a Audible plus title is removed from audible plus. 

A similar enhancement would be to warn users if an owned book has been delisted and relisted on audibles website, so they do not accidentally rebuy something they already own. 

Reddit links for reference about the issue

Removed from library: https://www.reddit.com/r/audible/comments/t4m4qb/pa_a_bunch_of_titles_were_missing_from_my_library/

Delisted: https://www.reddit.com/r/audible/comments/t4wrre/when_audible_removes_an_audiobook_from_their_site/

**Comment by JyeGuru** [comment] 2022-03-03 04:25
> This functionality should not warn users if a Audible plus title is removed from audible plus.

I personally would like to be notified about this, so an option (disabled by default) would be helpful.

**Comment by rmcrackan** [comment] 2022-07-20 16:13
Duplicate of #269

**Closed by rmcrackan** 2022-07-20 16:13 UTC
Labels: enhancement
