### ISSUE TITLE
Feature request: pseudo-characters which preserve appearance as an option

### ISSUE THREAD

**Issue by anthonynogales** [rmcrackan/Libation#285] opened 2022-06-21 15:27 UTC
I noticed last night after updating to version 8.1.0.2 that downloading an audiobook with colons in the name results in the folder and file name showing colons as well. I reported this on a Reddit [thread](https://www.reddit.com/r/audible/comments/vbi0f5/comment/id5f2zz/?utm_source=reddit&utm_medium=web2x&context=3) by darchangel. 

`..\Drew Karpyshyn - Star Wars꞉ The Old Republic꞉ Revan\Star Wars꞉ The Old Republic꞉ Revan [B005ZT0X1C].m4b
`

**Comment by Mbucari** [comment] 2022-06-21 15:34
It's a feature, not a bug. 

Illegal path characters are replaced with Unicode analogs. Replacements are as follows:

- : → [꞉](https://unicodes.jessetane.com/%EA%9E%89)
- \* → [✱](https://unicodes.jessetane.com/%E2%9C%B1)
- ? → [？](https://unicodes.jessetane.com/%EF%BC%9F)
- \< →[＜](https://unicodes.jessetane.com/%EF%BC%9C)
- \> → [＞](https://unicodes.jessetane.com/%EF%BC%9E)
- " → [“](https://unicodes.jessetane.com/%E2%80%9C), [”](https://unicodes.jessetane.com/%E2%80%9D), or [＂](https://unicodes.jessetane.com/%EF%BC%82)using some logic to detect open and closed quotes.

**Comment by Mbucari** [comment] 2022-06-21 15:39
It's on forever. I thought everyone would appreciate it so I didn't make it optional.  @rmcrackan @anthonynogales Should this be optional?

**Comment by anthonynogales** [comment] 2022-06-21 15:47
I'm at the very beginning of organizing my audiobook library so it makes no difference to me. The only reason I'd rename these would be if these characters didn't play well with Plex or Audiobookshelf BUT I don't expect there will be any issues. In fact, I think it's pretty awesome! Once I finish my testing I'll probably utilize this across the board since (novice that I am) I didn't realize I could replace the illegal characters with Unicode analogs. My default has been to replace ":" with " - ". 

Playing devil's advocate, the only people I see being peeved are the OCD folks who have already organized thousands of audiobooks and would have to rename the folders\files after they're downloaded or else update their existing folders to use the analogs. They're probably a minority though and if they're that OCD they could probably script a solution.

**Comment by Mbucari** [comment] 2022-06-21 15:53
> if these characters didn't play well with Plex or Audiobookshelf 

There's bound to be some software out there that still only uses ANSI strings, but they are probably either very old or pieces of junk in general. 15 years ago this might have been a problem, but these days nearly all modern software use Unicode internally.

But you make a good point about those annoying OCD people lol.

**Comment by wtanksleyjr** [comment] 2022-06-21 16:02
My initial reaction was REALLY negative, but then I chilled -- this will
only matter to people who explicitly enable the renaming, so they can
actually expect this kind of change.

If I had to deal with this in my scripts, though, it would simply be the
end of my scripts, it doesn't matter how OCD you are if you cannot even
tell why your regexps are failing to match.

**Comment by Mbucari** [comment] 2022-06-21 16:10
> For the record to the OCDs out there, I'm one of them.

I really was joking. OCD people are the ones who make bug reports and feature requests because they like things just so. Non-OCD people see something they don't like and usually just shrug and deal with it. I fall on the OCD side.

> act up on both Android and iOS file systems and then on drives formatted in exfat, zfs, btrfs, ext4, and whatever macOS is using these days

I checked, and all major file systems support Unicode paths. Additionally, >90% of Android software is written in Java, and all Java strings are Unicode so the devs don't even need to think about it for it to work. I know nothing about IOS, but Apple is not stupid and quite modern (bleeding edge, even), so I expect the same is true in their ecosystem.

@wtanksleyjr 

Sorry about that.  If you do use this feature in the future, would you be able to adjust your scripts to cope or would you just want an option to do standard illegal character replacement (e.g. _)?

**Comment by wtanksleyjr** [comment] 2022-06-21 16:22
Like I said, someone who's doing renaming using their own script anyhow
would just have to deal with the file as it appears, and would probably use
the metadata in the JSON export to decide what the new name should be.

It would be nice, though, to have a lo-fi option in addition to the 16-bit
hifi characters :) . So I'd vote in favor of being able to "filter out"
illegal characters with underscores, as you suggest.

-Wm

**Comment by rmcrackan** [comment] 2022-06-21 17:15
I'm ambivalent. This is great for people who want it look the same, bad for people who want it to remain pure, and hell for anyone wanting to program against the results.

Personally, I'd prefer to know what I'm really looking at. Seeing a colon that's not really a colon or a question mark which isn't really a question mark raises red flags for me because of my history in security and programming. These are the kinds of tricks scammers use to avoid detection and the things pranksters use to punk their coworkers (google: `greek semicolon prank`). Outside of malice it can simply make debugging a nightmare as you pour through code looking for something which doesn't exist. Similarly a simple search fails because you search for what you think the character is. Likewise for if someone later is trying to script against our output.

On the other hand, people like me are the vocal minority. I'm sure plenty of folks want their stuff to 'just work'.

I'd like this option to be a future feature.

**Comment by anthonynogales** [comment] 2022-06-21 17:33
Understood! I think I'll dream up some scenarios to script with Bash and PowerShell tonight to make sure I understand how to do that properly. You mentioned creating a future feature? Want me to create one to toggle this feature on/off if there isn't one created already?

**Comment by Mbucari** [comment] 2022-06-22 00:54
I've put together a new illegal character replacement in my repo.  Can you download it and take it for a spin?  Settings are accessed from the Download and Decrypt tab. I'm out of the office all day tomorrow, so I'm not available for any help/debugging.

**Comment by rmcrackan** [comment] 2022-06-22 01:13
> Can you download it and take it for a spin?

I'll try but no promises. My job has been stupid busy lately. Tight deadline, one out on parental leave, one not yet fully trained, another on vacation, and something going around which I assume is covid taking out a not insignificant portion of our staff. My Libation time has been low lately.

**Comment by rmcrackan** [comment] 2022-06-24 00:57
Will be included in next release. Thanks @Mbucari !

**Closed by rmcrackan** 2022-06-24 00:57 UTC
Labels: enhancement
