### ISSUE TITLE
Unable to log in to audible.co.uk

### ISSUE THREAD

**Issue by dfuk** [rmcrackan/Libation#108] opened 2021-09-08 22:44 UTC
Hi I cant login to audible.co.uk using my pre amazon account name,  Libation asks for the password then crashes when I attempt to import with a dialog box that contains:

Could not register

   at AudibleApi.Authorization.Authorize.RegisterAsync(AccessToken accessToken, IEnumerable`1 cookies)
   at AudibleApi.Authorization.IdentityMaintainer.RegisterAsync()
   at AudibleApi.Authorization.IdentityMaintainer.CreateAsync(IIdentity identity, IAuthorize authorize, ISystemDateTime systemDateTime)
   at AudibleApi.Authorization.IdentityMaintainer.CreateAsync(IIdentity identity)
   at AudibleApi.EzApiCreator.createApiAsync(IIdentity identity)
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath, ILoginCallback loginCallback)
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 139
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 88
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\Dialogs\IndexLibraryDialog.cs:line 35

I have uploaded the verbose log file.
Please let me know if you require more information.

Thanks 

David Anderson

[Log202109.log](https://github.com/rmcrackan/Libation/files/7132148/Log202109.log)

**Comment by rmcrackan** [comment] 2021-09-16 12:13
Duplicate of #118

**Closed by rmcrackan** 2021-09-16 12:13 UTC

**Comment by rmcrackan** [comment] 2021-09-20 19:50
New login method available which should fix all current log in issues. See latest release [v6.0.1](https://github.com/rmcrackan/Libation/releases/tag/v6.0.1). Thank you all for your patience while I worked to fix these.
