### ISSUE TITLE
M4B created by Libation will not convert to MP3 using inAudible.

### ISSUE THREAD

**Issue by chieftwidgit** [rmcrackan/Libation#528] opened 2023-03-13 17:48 UTC
A small number of M4B files created by inAudible can't be converted to MP3 by inAudible or AVS Audio converter or Total Audio converter.
This one is my latest headache
Architects of the Apocalypse, Book 3
By: Jasper T. Scott](https://www.audible.com/author/Jasper-T-Scott/B00B7A2CT4

Narrated by: [James Patrick Cronin]
Series: [Architects of the Apocalypse] Book 3

Below is some pointers on the issue.
I took a look at this file.  It looks like there are some bugs in Libation. 

    First of all, the filename contains the character ":".  This is an illegal character in a file name in Windows.  I'm guessing that this was converted on the Linux version of the program.  If you replace the colon with a dash, that lets the libraries process the file correctly.
    The description of the file is full of illegal characters, most importantly \n & ". The former is the code used for a new line, the latter, the code to "escape" or quote a quote.  If you edit the description to remove these, the file processes fine.

The original description:

From million-copy best seller Jasper T. Scott.\nThe Architects are about to be revealed.\nWith the discovery of the so-called "living water" on Novus, three different superpowers are competing for the one small valley where the miracle elixir can be found. From the United States, Major Ethan White is heading up a company of elite Army Rangers charged with claiming the valley for America, but with Earth overrun by the Watchers, he's now looking for a way to go back and join the fight.\nLayla Bester just wants to keep her baby girl safe, and Tom Smith is determined to help her. Having learned who the girl’s father really is, Layla is on the run, but it’s not easy to find refuge in a world that is teeming with deadly creatures. To make matters worse, the shadowy specter that was stalking her on Earth appears to have followed her to Novus, and now there is more than one.\nMeanwhile, the Watchers have their own plans for Novus and its people. A war is coming, and the winner will determine the fate of the entire human race.\nApokalypsis is the shocking conclusion to the best-selling series Architects of the Apocalypse by Jasper T. Scott. If you liked Under the Dome by Stephen King or the Maze Runner by James Dashner, then this book is for you.

The proper description:

From million-copy best seller Jasper T. Scott.

The Architects are about to be revealed.

With the discovery of the so-called "living water" on Novus, three different superpowers are competing for the one small valley where the miracle elixir can be found. From the United States, Major Ethan White is heading up a company of elite Army Rangers charged with claiming the valley for America, but with Earth overrun by the Watchers, he's now looking for a way to go back and join the fight.

Layla Bester just wants to keep her baby girl safe, and Tom Smith is determined to help her. Having learned who the girl’s father really is, Layla is on the run, but it’s not easy to find refuge in a world that is teeming with deadly creatures. To make matters worse, the shadowy specter that was stalking her on Earth appears to have followed her to Novus, and now there is more than one.

Meanwhile, the Watchers have their own plans for Novus and its people. A war is coming, and the winner will determine the fate of the entire human race.

Apokalypsis is the shocking conclusion to the best-selling series Architects of the Apocalypse by Jasper T. Scott. If you liked Under the Dome by Stephen King or the Maze Runner by James Dashner, then this book is for you.

**Comment by chieftwidgit** [comment] 2023-03-13 18:27
I edited the meta data and removed the ":" and the file would convert to MP3.

**Comment by Mbucari** [comment] 2023-03-13 20:06
@chieftwidgit I'm a bit confused. Are you using Libation, inAudible, or both?

## Re "_I'm guessing that this was converted on the Linux version of the program._"

Libation replaces characters that are illegal on the platform it's running on. Users can also specify other legal characters to replace in the settings, so if you want to can add the colon as a character to replace and define what it's replaced with.

## Regarding the description text

Libation doesn't alter description text (or most other metadata properties for that matter). If that's what's displaying it's because that's what was in the aax file that audible served you.You can verify this for yourself by enabling the "Retain the Aax file after successfully decrypting" option then reading the metadata from it. Aax files are just encrypted mp4 files, so you can use whatever metadata reader you want.

**Comment by chieftwidgit** [comment] 2023-03-13 20:17
I am using both yes.  But this file was passed to me to try and determine
why it would not convert.  I simply download Audible Plus and KU included
files with Libation, everything else my browser saves to disk and I use
inAudible.

**Comment by Mbucari** [comment] 2023-03-13 20:43
Can you please send me one of the affected files? I really can't diagnose a bad file format without having access to the file.

https://wetransfer.com/ lets you send files up to 2GB for free.

**Comment by Mbucari** [comment] 2023-03-13 21:13
@chieftwidgit How did you send the file? My email address is mbucari1@gmail.com. Audio files are my bailiwick, so @rmcrackan won't be able to help much.

**Comment by chieftwidgit** [comment] 2023-03-13 21:24
Yes, I sent it.   https://we.tl/t-j0Sc0Z3r8W

You should have sent your email previously.  Sorry.

**Comment by Mbucari** [comment] 2023-03-13 21:36
OK, one more question. When you're trying to convert this file to mp3, are you trying splitting it by chapter? And if so, are is the program trying to use the chapter titles as file names? If both answers are yes, then that's your problem. That book's chapter titles have colons in them. If your encoder program isn't replacing those before trying to write the file, then it fail on windows.

If you really want to use a different program to convert audiobooks to mp3 (as opposed to Libation's built-in mp3 converter), I suggest setting Libation to splitthe m4b file into chapters. Libation will handle character replacements for you. Then you can convert those chapter files into mp3.

**Comment by chieftwidgit** [comment] 2023-03-13 21:42
The program converted the file after correcting the title (by removing the
colon), it pretty much ignores the chapter name, but will look into that.
(I am not the programmer but was in touch with TorqueMurder) who wrote
inAudible.  I did not convert the original file, I was only trying to
figure out why it would not convert.  I have run into a very small number
of Libation M4B files that hang inAudible, but some of them I already had
the .AAX from when the Win10 app still worked.  So not a major issue.  The
original work around was to convert the M4B to M4B chapterized in inAudible
(which worked) and then convert that to MP3.

Ask any question you wish.  I am willing to work with you to eradicate any
bugs crawling around even if they are "features".

**Comment by chieftwidgit** [comment] 2023-03-13 21:43
As for why convert.  Some people like M4B, but others want MP3 and you
can't do both at the same time with Libation.

**Comment by Mbucari** [comment] 2023-03-13 23:12
@chieftwidgit I've confirmed that the colons in the chapter titles is what's causing error in both inAudible and AVS Audio Converter. I don't know why it's a problem for them, but it is most assuredly _their_ problem. Libation is working as intended.

**Comment by rmcrackan** [comment] 2023-03-14 01:36
@Mbucari Thanks for clarifying that this isn't an issue in Libation. I'm going to close this.

@chieftwidgit Please extend my gratitude to the author of inAudible. His program was a huge inspiration of mine when I created Libation and I'm so very thankful for his work.

Regarding both m4b and mp3: if it were me, I'd do all of my decrypting in Libation in one format. Then use the 'visible books' menu to set all books to not downloaded. Change the settings to do the other format. And lastly do a new full download as the new format. It's a few steps but this would batch convert any number of books for you.

**Closed by rmcrackan** 2023-03-14 01:36 UTC
Labels: bug
