### ISSUE TITLE
Apply new filename/foldername pattern to already liberated books

### ISSUE THREAD

**Issue by stranno** [rmcrackan/Libation#414] opened 2022-12-18 13:19 UTC
I was wondering if there's a possibility to add an option to check the filename structure of all downloaded files and apply the new changes to old files, including the filename and folder name pattern, also the folder icon on Windows or the illegal characters swapping pattern.

Thank you rmcrackan.

**Comment by rmcrackan** [comment] 2023-01-09 18:21
Duplicate of #426

**Comment by rmcrackan** [comment] 2023-01-09 18:22
In practice, fixing this will be the same as issue #426 -- so I'm combining them so that we can track in one place.

**Closed by rmcrackan** 2023-01-09 18:21 UTC
Labels: enhancement
