### ISSUE TITLE
Approved

### ISSUE THREAD

**Issue by ueen** [rmcrackan/Libation#18] opened 2020-12-08 17:21 UTC
I'm getting a error after approving E-Mail verification by Amazon and the Librarys fails to scan, this happens on a second account.

**Comment by mkb79** [comment] 2020-12-08 17:54
Hi. Take a look to [#16](https://github.com/rmcrackan/Libation/issues/16). It seems that’s the same error than yours. 

Best Grüße

**Comment by rmcrackan** [comment] 2020-12-08 18:08
As @mkb79 mentioned, this appears to be duplicate of #16 . If any progress is made, I'll be note it there.

**Closed by rmcrackan** 2020-12-08 18:08 UTC

**Comment by ueen** [comment] 2020-12-08 18:19
Oh i didnt know, doesnt it makes sense to keep the issue open until its resolved? So not to have duplicates?

**Comment by rmcrackan** [comment] 2020-12-08 18:25
Sadly, the resolution for now is: closing because I can't fix it.

Libation is a single developer, unpaid, reverse engineer project and this
is an issue that I've invested months of time in while making no progress.
I'm closing this because I'm done investing my time in it for now. There's
an argument to be made that this should stay open indefinitely until
resolved. However I'm of the opinion that 'open' implies probable future
progress.

>

**Comment by ueen** [comment] 2020-12-08 18:28
I dont know if this is helpful but i noticed that AMazon says: Approve or deny for iPhone App, might this have anything to do with it? Maybe check out what OpenAudible is doing, it just presents audible in a webview so you can log in and then probably catches some cookie or so (i think its called tha auth code)

**Comment by ueen** [comment] 2020-12-08 18:30
Well you dont have to do it, if its open somebody might help with a PR, isnt github supposed to be like that?

**Comment by mkb79** [comment] 2020-12-08 18:34
You can try to activate 2FA for your Amazon account. This should bypass the approval alert mail.

**Comment by ueen** [comment] 2020-12-08 18:35
Thats interesting, but i dont really give my tel number to amazon

**Comment by mkb79** [comment] 2020-12-08 18:37
Than use an app like Authy for iOS or similar. This apps create a one-time password for you.

**Comment by ueen** [comment] 2020-12-08 18:40
Its strange cause this only keeps happening with the second account the frist worked just fine, they're both german and its the same domin

**Comment by ueen** [comment] 2020-12-08 18:42
This seems promising though https://github.com/rmcrackan/Libation/issues/16#issuecomment-737263637 @rmcrackan wont you give it a final try? :D

**Comment by mkb79** [comment] 2020-12-08 18:44
I‘ve an german and an US account both with 2FA activated. Amazon doesn’t send me approval alerts until now.

**Comment by ueen** [comment] 2020-12-08 18:48
Ok this might be a workaround, but as this is a kind of shared account it would be very annoying with 2FA, i'll might try it out tough, thanks!

**Comment by ueen** [comment] 2020-12-08 18:51
Or heres another idea: maybe the auth code (which, correct me if i'm wrong is what we're after) could be entered manually, as a kind of fallback method?

**Comment by mkb79** [comment] 2020-12-08 19:03
I will try to explain it a little deeper. 

If Amazon think you are a bot or detects some suspect things during authorization, Amazon will protect your account with some mechanisms.

That’s the reason why you have to solve a captcha. In some circumstances Amazon asks for an additional authorization if you have 2FA deactivated. This could be an auth code, which Amazon sends you via mail or SMS. Or since short time, Amazon sends this approval alert mails.

**Comment by ueen** [comment] 2020-12-08 19:19
Ok i tried the link from the Logs and logged in, with captcha but Amazon says (just as the logs): 404 so somehow the link is wrong i assume? The link starts like this `https://www.amazon.de/ap/maplanding?openid.assoc_handle=amzn_audible_ios_de`

**Comment by mkb79** [comment] 2020-12-08 19:22
Take a look on the url query. There must be the access_token in it.

**Comment by mkb79** [comment] 2020-12-08 19:22
The 404 is correct.

**Comment by ueen** [comment] 2020-12-08 19:27
https://www.amazon.de/ap/maplanding?openid.assoc_handle=amzn_audible_ios_de&openid.claimed_id=https%3A%2F%2Fwww.amazon.de%2Fap%2Fid%2Famzn1.account.XXX&openid.identity=https%3A%2F%2Fwww.amazon.de%2Fap%2Fid%2Famzn1.account.XXX&openid.mode=id_res&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.op_endpoint=https%3A%2F%2Fwww.amazon.de%2Fap%2Fsignin&openid.response_nonce=2020-12-08T19%3A16%3A14Z-6274342212059684450&openid.return_to=https%3A%2F%2Fwww.amazon.de%2Fap%2Fmaplanding&openid.signed=assoc_handle%2Cclaimed_id%2Cidentity%2Cmode%2Cns%2Cop_endpoint%2Cresponse_nonce%2Creturn_to%2Cns.pape%2Cpape.auth_policies%2Cpape.auth_time%2Coa2.access_token%2Coa2.token_type%2Coa2.scope%2Ccaptcha_verified%2Csigned&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.pape.auth_policies=http%3A%2F%2Fschemas.openid.net%2Fpape%2Fpolicies%2F2007%2F06%2Fnone&openid.pape.auth_time=2020-12-08T19%3A16%3A14Z&openid.sig=XXX&serial=&openid.oa2.access_token=XXX&openid.oa2.token_type=bearer&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.scope=device_auth_access&captcha_verified=1& this is the link

**Comment by ueen** [comment] 2020-12-08 19:29
Theres the access_token.
So i get the impression theres an issue with AudibleApi? But i couldnt find it in the repo

**Comment by mkb79** [comment] 2020-12-08 19:29
This openid.oa2.access_token=XXX is your access token.

**Comment by ueen** [comment] 2020-12-08 19:32
Also strange the AccountsSettings.json looks excactly the same for the account working and the other

**Comment by ueen** [comment] 2020-12-08 19:35
Strange, it begins with Atza instead of Atna which seems to be the default according to `AccountsSettings.json`

**Comment by ueen** [comment] 2020-12-08 19:38
This might be it, if i enter the token manually to `AccountsSettings.json` on startup theres an error 
`System.ArgumentException: Improperly formatted access token (Parameter 'value')`
if i change to Atna (which obviously invalidates the token) it startsup just fine!

**Comment by mkb79** [comment] 2020-12-08 19:44
Maybe the scope of the tokens are different. The access_token with the scope `device_auth_access` starts with `Atna|`. This token can be used to register an Audible device. After an registration you got an refresh_token, which starts with `Atnr|`. This `Atza|` token I saw often in the cookies after an successful authorization (login), I think!

**Comment by ueen** [comment] 2020-12-08 19:52
Yea you're right i was looking at the cookies after login

**Comment by ueen** [comment] 2020-12-08 19:55
Well the only difference i can think about is that this account has a lot more books and a **podcast** in its library than the other account

**Comment by ueen** [comment] 2020-12-08 19:56
And maybe it was registered on an Android phone before, could there be like a limit of devices?

**Comment by mkb79** [comment] 2020-12-08 20:04
I had trouble after 7 or 8 active registered Audible devices in the past. Amazon requested a password change from me for 3 times in short time until I removed some devices. 

You can compare your accounts and take a look on the Audible devices list on Amazon.

**Comment by ueen** [comment] 2020-12-08 20:07
Ok there are only two for now

**Comment by ueen** [comment] 2020-12-08 20:12
Ok i suspect there might be something wrong with the return_to, as it is a 404, which isnt the expected result, is it?

**Comment by mkb79** [comment] 2020-12-08 20:12
Can you try this login url with Firefox and check if this gives you an valid access_token:

https://www.amazon.de/ap/signin?openid.oa2.response_type=token&openid.return_to=https%3A%2F%2Fwww.amazon.de%2Fap%2Fmaplanding&openid.assoc_handle=amzn_audible_ios_de&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_audible_ios&accountStatusPolicy=P1&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.mode=checkid_setup&openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&openid.oa2.client_id=device%3A6a52316c62706d53427a5735505a76477a45375959566674327959465a6374424a53497069546d45234132435a4a5a474c4b324a4a564d&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&marketPlaceId=AN7V1F1VY261K&openid.oa2.scope=device_auth_access&forceMobileLayout=true&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.pape.max_auth_age=0

**Comment by ueen** [comment] 2020-12-08 20:14
It does but its a 404 and the device doesnt show up in my Amazon Account so somethings not working

**Comment by mkb79** [comment] 2020-12-08 20:14
The 404 is correct for a `device_auth_access` authorization.

**Comment by mkb79** [comment] 2020-12-08 20:20
If you follow the link it gives you hopefully a valid `Atna|` access_token in the 404 url query. The device registration is an extra step where you need this access token. The access token is valid for 60 minutes!

PS: maybe you can write to me via mail to mkb79@hackitall.de so we don’t have to write this off-topic thinks in rmcrackan issue board.

**Comment by ueen** [comment] 2020-12-08 20:29
I'm sorry im not trying to get off topic, rather searching for the issue

**Comment by mkb79** [comment] 2020-12-08 20:31
If you don’t want to write me via mail you can open an issue on my [Audible](https://github.com/mkb79/Audible) package.

**Comment by ueen** [comment] 2020-12-08 20:32
Maybe theres an issue with the return_to link detection if you look at the link above it may be not clear how far the value for the link is going lik is it just
`https%3A%2F%2Fwww.amazon.de%2Fap%2Fmaplanding` or is it going further?

**Comment by mkb79** [comment] 2020-12-08 20:40
If you are on iOS you can install HTTP Catcher with full trusted root certs activated. Than you can dump all your decrypted `https` requests to Audible and Amazon. And you will see that the return_to url is correct. But if you login with the Audible iOS app you will see, that the app sends some cookies on login url request. I doesn’t know how this cookies can be rebuild.
