### ISSUE TITLE
Further Input on MP3 Incorrect Length in Foobar 2000

### ISSUE THREAD

**Issue by sgmax** [rmcrackan/Libation#110] opened 2021-09-10 21:26 UTC
I dug around in the Foobar 2k forums and other mp3 resources online. It appears that the problem is that your mp3 encode process does not add a Xing header to the encoded file. The Xing header provides extra information about the mp3 that is used by players and encoders for VBR file information, but is not officially part of the mp3 specification. 
I checked the Libation file encoding using the MP3 Diags utility (http://mp3diags.sourceforge.net/). It reported that "The MPEG audio stream uses VBR but a Xing header wasn't found. This will confuse some players, which won't be able to display the song duration or to seek."
*** It is clear that the Foobar 2k developers do NOT consider the inability to play mp3s without this header to be a bug in their player software. They discovered the issue around 2010 and their response was to provide a utility to fix the file. (This information is usefully buried in their bug reports). ***
I am filing a new issue (the previous one was closed), as this is a wider issue than Foobar-2k's ability to detect the correct length. Other players may fall over this problem. You may just want to make a note in the user documentation that some mp3 players (e.g. Foobar 2k) will report the length incorrectly and only play part of the file as a result. Users can fix this issue by right-clicking on the track in Foobar, selecting Utilities, then selecting "Fix VBR mp3 header." 
Or you may want to add a Xing header to the mp3 encoding. See the details at https://eyed3.readthedocs.io/en/latest/plugins/lameinfo_plugin.html and http://gabriel.mp3-tech.org/mp3infotag.html

**Comment by rmcrackan** [comment] 2021-09-10 21:42
Duplicate of #104

**Comment by rmcrackan** [comment] 2021-09-10 21:43
Since there's so much already in that other thread, I'll close this as duplicate and re-open that one

**Closed by rmcrackan** 2021-09-10 21:42 UTC

**Comment by sgmax** [comment] 2021-09-10 21:57
If you want any help, let me know. I'm *really* bad at C# coding, but I can
dig around for additional info if you need it.
Lots of discussion of this issue in Foobar forums. Some users consider it a
bug, but dev consensus is that it's a problem with mp3 files being poorly
formed.
It may be enough just to add this information to the documentation!

Cheers,
            Susan

**Comment by rmcrackan** [comment] 2021-09-11 03:22
Thank you for your research. I'm hopeful that the guy who specializes in the audio specs will see your comments in the other thread.

Unfortunately, the reaction from foobar is to be expected: idealists scream that you didn't do it exactly right and pragmatists scream that 'exactly right' isn't representative of the real world -- and they both have a point. Sadly, those of us in the middle suffer from both sides when we just want to help users.

**Comment by rmcrackan** [comment] 2021-09-16 11:58
Fixed in [v5.7.5](https://github.com/rmcrackan/Libation/releases/latest)
