### ISSUE TITLE
Track Book Availability

### ISSUE THREAD

**Issue by manalive** [rmcrackan/Libation#499] opened 2023-02-16 12:58 UTC
**Is your feature request related to a problem? Please describe.**

There are books in my library that are 

1. no longer available for download
2. not available for download yet but have an arrival date in the future (Coming Soon and Pre-Orders)
3. available for download now but will be removed at a future date

This is relevant because:
- I need to know not to delete books in the first category (thinking I can redownload them).
- Libation doesn't need to be trying to download books in the second category before they are available (and I don't need to worry about why they aren't downloading).
- I want to prioritize books in category 3

**Describe the solution you'd like**
If you can do it with one field, that would be clever and awesome but otherwise, I would think 3 make sense:

- Available (boolean)
- Date Removed (Available Until)
- Date Available (Available From)

**Comment by rmcrackan** [comment] 2023-02-16 13:00
Duplicate of #269

**Comment by rmcrackan** [comment] 2023-02-16 13:01
This isn't identical to #269 but it's close enough that this will link the 2 and they can be addressed together.

**Closed by rmcrackan** 2023-02-16 13:00 UTC
Labels: enhancement
