### ISSUE TITLE
Audible's CATPCHA not recognising correct answers

### ISSUE THREAD

**Issue by Ozymandiaz** [rmcrackan/Libation#109] opened 2021-09-10 00:51 UTC
CATPCHA challenge not recognising correct answers
[Log202109.log](https://github.com/rmcrackan/Libation/files/7140487/Log202109.log)

**Comment by rmcrackan** [comment] 2021-09-10 01:00
By design, I can only see your username masked. The ending looks very odd. Is it correct?

> d[...]n@s[...]t.c[...]m/~[...]!

**Comment by Ozymandiaz** [comment] 2021-09-10 04:00
Regards,

*Duncan*

*M: * 0408 096 111
*E: ***@***.*** ***@***.***>*
**S: * duncan-jones*
*L: View Duncan's profile on LinkedIn at https://au.linkedin.com/pub/duncan-jones/b/787/71a <https://au.linkedin.com/pub/duncan-jones/b/787/71a>*

**Comment by rmcrackan** [comment] 2021-09-10 11:54
I think only your email signature came through. Please try again

**Comment by Jimmni** [comment] 2021-09-12 19:54
I am also failing to log in. I tried three different accounts in two different regions. All repeatedly asked for new captchas until failure. I can log in to the accounts using Firefox with the same details without issue.

[Log202109.log](https://github.com/rmcrackan/Libation/files/7150202/Log202109.log)

**Comment by aLEKsITH1** [comment] 2021-09-16 06:48
you should only log in on the app not the Browser as far as I know

**Comment by rmcrackan** [comment] 2021-09-16 12:13
Duplicate of #118

**Closed by rmcrackan** 2021-09-16 12:13 UTC

**Comment by rmcrackan** [comment] 2021-09-20 19:50
New login method available which should fix all current log in issues. See latest release [v6.0.1](https://github.com/rmcrackan/Libation/releases/tag/v6.0.1). Thank you all for your patience while I worked to fix these.
